fora/urls.py
from django.conf.urls import url

from fora import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_comment/(?P<forum_id>\d+)-(?P<reply_to_id>\d+)/$',
        views.add_comment, name='add_comment'),
    url(r'^add_thread/(?P<forum_id>\d+)/$',
        views.create_thread, name='create_thread'),
    url(r'^view_thread/(?P<thread_id>\d+)/$',
        views.view_thread, name='view_thread'),
    url(r'^hide_comment/(?P<comment_id>\d+)/$',
        views.hide_comment, name='hide_comment'),
    url(r'^upvote_comment/(?P<comment_id>\d+)/$',
        views.upvote_comment, name='upvote_comment'),
    url(r'^downvote_comment/(?P<comment_id>\d+)/$',
        views.downvote_comment, name='downvote_comment'),
    url(r'^withdraw_upvote/(?P<comment_id>\d+)/$',
        views.withdraw_upvote, name='withdraw_upvote'),
    url(r'^withdraw_downvote/(?P<comment_id>\d+)/$',
        views.withdraw_downvote, name='withdraw_downvote'),
    url(r'^new_forum/$', views.create_forum, name='create_forum'),
    url(r'^delete_forum/(?P<forum_id>\d+)/$',
        views.delete_forum, name='delete_forum'),
    url(r'^get_thread_page/(?P<forum_id>\d+)-(?P<page_num>\d+)/$',
        views.get_thread_page, name='get_thread_page'),
    url(r'^map/$', views.view_map, name='view_map'),
]

history/urls.py
from django.conf.urls import url

from history import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^article/(?P<article_id>\d+)/$',
        views.article_view,
        name='article_view'),
    url(r'^cornerstone/$',
        views.cornerstone_view,
        name='cornerstone_view'),
    url(r'^alumninews/$',
        views.alumninews_view,
        name='alumninews_view'),
    url(r'^view_project_reports/$',
        views.get_project_reports,
        name='get_project_reports'),
    url(r'^upload_article/$',
        views.upload_article,
        name='upload_article'),
    url(r'^start_project_reports/(?P<term_id>\d+)/$',
        views.start_project_report_compilation,
        name='start_project_report_compilation'),
    url(r'^process_project_reports/$',
        views.process_project_report_compilation,
        name='process_project_report_compilation'),
    url(r'^process_reports/(?P<prh_id>\d+)-(?P<pr_id>\d+)/$',
        views.process_project_reports,
        name='process_project_reports'),
    url(r'^process_report_photos/(?P<prh_id>\d+)-(?P<pr_id>\d+)/$',
        views.process_project_report_photos,
        name='process_project_report_photos'),
    url(r'^compile_reports/(?P<prh_id>\d+)/$',
        views.compile_project_reports,
        name='compile_project_reports'),
    url(r'^edit_stories/$',
        views.edit_articles,
        name='edit_articles'),
]

member_resources/urls.py
from django.conf.urls import url

from member_resources import views

urlpatterns = [
	url(r'^$',
        views.index, name='index'),
	url(r'^profiles/$',
        views.member_profiles, name='member_profiles'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/$',
        views.profile, name='profile'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/edit/$',
        views.profile_edit, name='profile_edit'),
    url(r'^profiles/create$',
        views.profile_create, name='profile_create'),
    url(r'^progress/(?P<uniqname>[a-z]{3,8})/$',
        views.view_progress,
        name='view_progress'),
    url(r'^track_my_progress/$',
        views.track_my_progress,
        name='track_my_progress'),
    url(r'^edit_progress/(?P<uniqname>[a-z]{3,8})/$',
        views.edit_progress,
        name='edit_progress'),
    url(r'^progress_list/$',
        views.view_progress_list,
        name='view_progress_list'),
    url(r'^progress_table/$',
        views.view_progress_table,
        name='view_progress_table'),
    url(r'^manage_misc_reqs/$',
        views.view_misc_reqs,
        name='view_misc_reqs'),
    url(r'^history_reports/$',
        views.access_history,
        name='access_history'),
    url(r'^approve_tutoring/$',
        views.approve_tutoring_forms,
        name='approve_tutoring_forms'),
    url(r'^electees_stopping_electing/$',
        views.handle_electees_stopping_electing,
        name='handle_electees_stopping_electing'),
    url(r'^manage_active_group_meetings/$',
        views.manage_active_group_meetings,
        name='manage_active_group_meetings'),
    url(r'^manage_project_leaders/$',
        views.manage_project_leaders,
        name='manage_project_leaders'),
    url(r'^add_active_statuses/$',
        views.add_active_statuses,
        name='add_active_statuses'),
    url(r'^add_active_statuses_for_term/(?P<term_id>\d+)/$',
        views.add_active_statuses_for_term,
        name='add_active_statuses_for_term'),
    url(r'^edit_active_statuses/$',
        views.manage_active_statuses,
        name='manage_active_statuses'),
    url(r'^move_electees_to_active/$',
        views.move_electees_to_active,
        name='move_electees_to_active'),
    url(r'^add_electee_DAPA/$',
        views.add_electee_DA_PA_status,
        name='add_electee_DA_PA_status'),
    url(r'^add_leadership_credit/$',
        views.add_leadership_credit,
        name='add_leadership_credit'),
    url(r'^change_requirements/(?P<distinction_id>\d+)/$',
        views.change_requirements,
        name='change_requirements'),
    url(r'^change_event_categories/$',
        views.change_event_categories,
        name='change_event_categories'),
    url(r'^manage_officers/(?P<term_id>\d+)/$',
        views.manage_officers,
        name='manage_officers'),
    url(r'^meeting_feedback/(?P<term_id>\d+)/$',
        views.view_meeting_feedback_for_term,
        name='view_meeting_feedback_for_term'),
    url(r'^meeting_feedback/$',
        views.view_meeting_feedback,
        name='view_meeting_feedback'),
    url(r'^manage_dues/$',
        views.manage_dues,
        name='manage_dues'),
    url(r'^add_actives/$',
        views.add_to_active_list,
        name='add_to_active_list'),
    url(r'^edit_member_lists/$',
        views.edit_list,
        name='edit_list'),
    url(r'^clear_electee_lists/$',
        views.clear_electee_lists,
        name='clear_electee_lists'),
    url(r'^add_ugrad_electees/$',
        views.add_to_ugrad_electee_list,
        name='add_to_ugrad_electee_list'),
    url(r'^add_grad_electees/$',
        views.add_to_grad_electee_list,
        name='add_to_grad_electee_list'),
    url(r'^manage_website/$',
        views.manage_website,
        name='manage_website'),
    url(r'^advance_term/$',
        views.advance_term,
        name='advance_term'),
    url(r'^manage_electee_paperwork/$',
        views.manage_electee_paperwork,
        name='manage_electee_paperwork'),
    url(r'^download_active_progress/$',
        views.download_active_progress,
        name='download_active_progress'),
    url(r'^download_grad_el_progress/$',
        views.download_grad_el_progress,
        name='download_grad_el_progress'),
    url(r'^download_ugrad_el_progress/$',
        views.download_ugrad_el_progress,
        name='download_ugrad_el_progress'),
    url(r'^officer_minutes/$',
        views.officer_meeting_minutes,
        name='officer_meeting_minutes'),
    url(r'^advisory_board_minutes/$',
        views.advisory_board_meeting_minutes,
        name='advisory_board_meeting_minutes'),
    url(r'^meeting_minutes/$',
        views.main_meeting_minutes,
        name='main_meeting_minutes'),
    url(r'^NI_minutes/$',
        views.new_initiatives_meeting_minutes,
        name='new_initiatives_meeting_minutes'),
    url(r'^committee_minutes/$',
        views.committee_meeting_minutes,
        name='committee_meeting_minutes'),
    url(r'^upload_minutes/$',
        views.upload_minutes,
        name='upload_minutes'),
    url(r'^update_preferences/$',
        views.update_preferences,
        name='update_preferences'),
    url(r'^list_project_reports/$',
        views.project_reports_list,
        name='project_reports_list'),
    url(r'^add_external_service/$',
        views.add_external_service,
        name='add_external_service'),
    url(r'^grad_background_forms/$',
        views.view_background_forms,
        name='view_background_forms'),
    url(r'^give_tbpraise/$',
        views.submit_praise,
        name='submit_praise'),
    url(r'^approve_tbpraise/(?P<praise_id>\d+)/$',
        views.approve_praise,
        name='approve_praise'),
    url(r'^new_non_event_project/$',
        views.new_non_event_project,
        name='new_non_event_project'),
    url(r'^non_event_project/(?P<ne_id>\d+)/$',
        views.non_event_project,
        name='non_event_project'),
    url(r'^non_event_project_participants/(?P<ne_id>\d+)/$',
        views.non_event_project_participants,
        name='non_event_project_participants'),
    url(r'^manage_awards/(?P<term_id>\d+)/$',
        views.manage_awards_for_term,
        name='manage_awards_for_term'),
    url(r'^manage_awards/$',
        views.manage_awards,
        name='manage_awards'),
    url(r'^view_electee_surveys/(?P<term_id>\d+)/$',
        views.view_electee_surveys_for_term,
        name='view_electee_surveys_for_term'),
    url(r'^view_electee_surveys/$',
        views.view_electee_surveys,
        name='view_electee_surveys'),
    url(r'^manage_background_checks/$',
        views.add_background_checks,
        name='add_background_checks'),
    url(r'^manage_many_background_checks/$',
        views.mass_add_background_checks,
        name='mass_add_background_checks'),
    url(r'^download_member_data/$',
        views.download_member_data,
        name='download_member_data'),
    url(r'^download_member_data_email/$',
        views.download_member_data_email,
        name='download_member_data_email'),
    url(r'^download_active_status/$',
        views.download_active_status,
        name='download_active_status'),
    url(r'^download_elections_voters/$',
        views.download_elections_voters,
        name='download_elections_voters'),
    url(r'^view_electee_survey/(?P<uniqname>[a-z]{3,8})/$',
        views.view_electee_survey,
        name='view_electee_survey'),
    url(r'^manage_committee_members/(?P<term_id>\d+)/$',
        views.manage_committee_members,
        name='manage_committee_members'),
    url(r'^edit_project_reports/(?P<term_id>\d+)/$',
        views.edit_project_reports,
        name='edit_project_reports'),
    url(r'^manage_committees/$',
        views.manage_committees,
        name='manage_committees'),
    url(r'^view_photos/$',
        views.view_photos,
        name='view_photos'),
    url(r'^manage_alumni_status/$',
        views.manage_alumni_status,
        name='manage_alumni_status'),
]

migweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from migweb import views
from event_cal import views as ev_views
admin.autodiscover()

urlpatterns = [
    url(r'^$',
        views.home, name='home'),
    url(r'^career_fair/companies/$',
        views.cf_companies, name='cf_companies'),
    url(r'^about/',
        include('about.urls', namespace='about')),
    url(r'^outreach/',
        include('outreach.urls', namespace='outreach')),
    url(r'^publications/',
        include('history.urls', namespace='history')),
    url(r'^corporate/',
        include('corporate.urls', namespace='corporate')),
    url(r'^calendar/',
        include('event_cal.urls', namespace='event_cal')),
    url(r'^members/elections/',
        include('elections.urls', namespace='elections')),
    url(r'^members/electees/',
        include('electees.urls', namespace='electees')),
    url(r'^members/playground/',
        include('fora.urls', namespace='fora')),
    # url(r'^bookswap/',
        # include('bookswap.urls', namespace='bookswap')),
    url(r'^members/',
        include('member_resources.urls', namespace='member_resources')),
    #url(r'^admin/plate/', include('django_spaghetti.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', views.login_view, name='login_view'),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'mig_main/login.html'}),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^oauth2callback/$', ev_views.oauth, name='oauth'),
    url(r'^townhalls/$', RedirectView.as_view(url='/outreach/townhalls/')),
    url(r'^pi_day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^pi-day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^piday/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^twitter_oauth/$',
        views.twitter_oauth,
        name='twitter_oauth'),
    url(r'^init_twitter/$',
        views.initialize_twitter,
        name='initialize_twitter'),
    url(r'^slide_ajax/(?P<slide_id>\d+)/$',
        views.get_slide_ajax,
        name='get_slide_ajax'),
    url(r'^photo_ajax/(?P<photo_id>\d+)/$',
        views.get_eventphoto_ajax,
        name='get_eventphoto_ajax'),
    url(r'^article_photo_ajax/(?P<photo_id>\d+)/$',
        views.get_article_photo_ajax,
        name='get_article_photo_ajax'),
    url(r'^select2/', include('django_select2.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

history/templates/history/base_history.html
{% extends "base.html" %}
{% block subnav_class %}subnav-small{%endblock%}
{% block subnav %}
{% for link in mig_dropdowns.publications %}
<li {%if subnav and subnav == link.subnav %}class="active"{% endif %}><a href="{{link.link}}">{{link.link_name}}</a></li>
{% endfor %}
{% endblock %}

history/templates/history/compiled_project_reports.html
{% extends "history/base_history.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-12">
{% if can_process_project_reports %}
    <a class="btn btn-warning" href="{% url 'history:process_project_report_compilation' %}">Assemble Project Reports</a>
{% endif %}
<h3>{{page_title}}</h3>
{% if reports %}
{% for report in reports %}
<p><a href="{{report.pdf_file.url}}">{{report}}</a></p>
{%endfor %}
{%endif%}
    </div>
</div>
{% endblock content %}

history/templates/history/printed_publications.html
{% extends "history/base_history.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-12">
<h3>{{page_title}}</h3>
{% if post_button %}
<p><a class="btn btn-default" href={% url 'history:upload_article' %}>Upload Edition of &quot;{{page_title}}&quot;</a></p>
{% endif %}
    </div>
</div>
    {% if articles %}
    {% regroup articles|dictsortreversed:"volume_number" by volume_number as articles_by_volume %}
    {% for volume in articles_by_volume %}
        {% if forloop.counter0|divisibleby:"6" %}
        <div class="row">
        {% endif %}
        <div class="col-md-2">
            <h5>Volume {{volume.grouper}}</h5>
            {% for edition in volume.list|dictsort:"edition_number" %}
                <p><a href="{{edition.pdf_file.url}}">{{edition.name}}</a></p>
            {% endfor %}
        </div>
        {% if forloop.counter|divisibleby:"6" or forloop.last%}
        <hr>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
{% endblock content %}

history/templates/history/project_report_compilation_manager.html
{% extends "history/base_history.html" %}
{% load staticfiles %}
{% load my_markdown %}

{% block content %}
<div class="row">
    {% if fall_term %}
    <div class="col-md-6">
        <h3>Fall Term Checkpoint Reports</h3>
        {% if pr_fall %}
        <p><a class="btn btn-success" href={% url 'history:start_project_report_compilation' fall_term.id %}>Edit Overview Information</a></p>
            
            {% if pr_fall.finished_processing %}
                <p><a class="btn btn-success" href={% url 'history:process_project_reports' pr_fall.id 0 %}>Process Reports from beginning</a></p>
                {% if pr_fall.finished_photos %}
                    <p><a class="btn btn-success" href={% url 'history:process_project_report_photos' pr_fall.id 0 %}>Process Photos from beginning</a></p>
                    <p><a class="btn btn-primary" href={% url 'history:compile_project_reports' pr_fall.id %}>Compile Reports (DO NOT REFRESH, This takes a few minutes.)</a></p>
                {% else %}
                    {% if pr_fall.last_photo %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_report_photos' pr_fall.id pr_fall.last_photo %}>Continue Processing Photos</a>
                    <a class="btn btn-primary" href={% url 'history:process_project_report_photos' pr_fall.id 0 %}>Process Photos from beginning</a></p>
                    
                    {% else %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_report_photos' pr_fall.id pr_fall.last_photo %}>Process Photos</a></p>

                    {% endif %}
            <p><button type="button" class="btn btn-default" disabled="disabled">Compile Reports</button></p>
                {% endif %}
            {% else %}
                {% if pr_fall.last_processed %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_reports' pr_fall.id pr_fall.last_processed %}>Continue Processing Reports</a>
                    <a class="btn btn-primary" href={% url 'history:process_project_reports' pr_fall.id 0 %}>Process Reports from beginning</a></p>
                {% else %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_reports' pr_fall.id pr_fall.last_processed %}>Process Individual Reports</a></p>
                {% endif %}
                    <p><button type="button" class="btn btn-default" disabled="disabled">Process Report Photos</button></p>
                    <p><button type="button" class="btn btn-default" disabled="disabled">Compile Reports</button></p>
                
            {% endif %}
        {% else %}
        <p><a type="button" class="btn btn-primary" href={% url 'history:start_project_report_compilation' fall_term.id %}>Start Project Report Compilation</a></p>
            <p><button type="button" class="btn btn-default" disabled="disabled">Process Individual Reports</button></p>
            <p><button type="button" class="btn btn-default" disabled="disabled">Process Report Photos</button></p>
            <p><button type="button" class="btn btn-default" disabled="disabled">Compile Reports</button></p>
        {% endif %}

    </div>
    {% endif %}
    {% if winter_term %}
    <div class="col-md-6">
        <h3>End of Year Reports</h3>
        {% if pr_winter %}
        <p><a class="btn btn-success" href={% url 'history:start_project_report_compilation' winter_term.id %}>Edit Overview Information</a></p>
            
            {% if pr_winter.finished_processing %}
                <p><a class="btn btn-success" href={% url 'history:process_project_reports' pr_winter.id 0 %}>Process Reports from beginning</a></p>
                {% if pr_winter.finished_photos %}
                    <p><a class="btn btn-success" href={% url 'history:process_project_report_photos' pr_winter.id 0 %}>Process Photos from beginning</a></p>
                    <p><a class="btn btn-primary" href={% url 'history:compile_project_reports' pr_winter.id %}>Compile Reports (DO NOT REFRESH, This takes a few minutes.)</a></p>
                {% else %}
                    {% if pr_winter.last_photo %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_report_photos' pr_winter.id pr_winter.last_photo %}>Continue Processing Photos</a>
                    <a class="btn btn-primary" href={% url 'history:process_project_report_photos' pr_winter.id 0 %}>Process Photos from beginning</a></p>
                    
                    {% else %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_report_photos' pr_winter.id pr_winter.last_photo %}>Process Photos</a></p>

                    {% endif %}
            <p><button type="button" class="btn btn-default" disabled="disabled">Compile Reports</button></p>
                {% endif %}
            {% else %}
                {% if pr_winter.last_processed %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_reports' pr_winter.id pr_winter.last_processed %}>Continue Processing Reports</a>
                    <a class="btn btn-primary" href={% url 'history:process_project_reports' pr_winter.id 0 %}>Process Reports from beginning</a></p>
                {% else %}
                    <p><a class="btn btn-primary" href={% url 'history:process_project_reports' pr_winter.id pr_winter.last_processed %}>Process Individual Reports</a></p>
                {% endif %}
                    <p><button type="button" class="btn btn-default" disabled="disabled">Process Report Photos</button></p>
                    <p><button type="button" class="btn btn-default" disabled="disabled">Compile Reports</button></p>
                
            {% endif %}
        {% else %}
        <p><a type="button" class="btn btn-primary" href={% url 'history:start_project_report_compilation' winter_term.id %}>Start Project Report Compilation</a></p>
            <p><button type="button" class="btn btn-default" disabled="disabled">Process Individual Reports</button></p>
            <p><button type="button" class="btn btn-default" disabled="disabled">Process Report Photos</button></p>
            <p><button type="button" class="btn btn-default" disabled="disabled">Compile Reports</button></p>
        {% endif %}

    </div>
    {% endif %}
</div>
{% endblock content %}

history/templates/history/publications.html
{% extends "history/base_history.html" %}
{% load staticfiles %}
{% load my_markdown %}

{% block js %}
<script>
    function addtext(img_url,img_title) {
        var newtext="!["+img_title+"]("+img_url+" \""+img_title+"\")\n";
        var caretPos = document.getElementById("id_body").selectionStart;
        var textAreaTxt = jQuery("#id_body").val();
        jQuery("#id_body").val(textAreaTxt.substring(0,caretPos)+newtext+textAreaTxt.substring(caretPos));
    }
    $(document).ready(function(){
    options={}
    options.onError=function(content){
        console.log(content);
    };
{% for photo in event_photos %}
{% if not forloop.first %}
    ajaxGet('{% url 'get_article_photo_ajax' photo.id %}', {},function(){
        },options);
{% endif %}
{% endfor %}
     });
</script>
{% endblock %}

{% block og_props %}

{% for news_article in web_articles %}
{% if main_id == 0 and  forloop.counter == 1 or main_id == news_article.id %}
<meta property="og:title" content="{{news_article.title}}"/>
<meta property="og:type" content="article" />
<meta property="og:url" content="https://tbp.engin.umich.edu{% url 'history:article_view' news_article.id %}" />
<meta property="og:image" content="https://tbp.engin.umich.edu{% static 'TBP_Logo.png' %}"/>
<meta property="og:description" content="{{news_article.get_short_view}}" />
{% endif %}
{% endfor %}
{% endblock%}

{% block content %}
{% if can_edit %}
<a href="{% url 'history:edit_articles' %}" class="btn btn-primary">Edit/Approve Stories ({{num_pending_stories}} Pending)</a>
{% endif %}
{% if can_post  and form %}
<div class="panel-group" id="newArticleAccordion">
    <div class="panel panel-default">
        <div class = "panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#newArticleAccordion" href="#collapseBody">
                    Post New Story
                </a>
            </h4>
        </div>
        <div id="collapseBody" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="dropdown">
                    <a class="btn btn-default" id="photoSelect" role="button" data-toggle="dropdown" href="#">Add Photo <span class="caret"></span></a>
                    <ul id="menu1" class="dropdown-menu scrollable-menu" role="menu" aria-labelledby="photoSelect">
                        {% for photo in event_photos %}
                        {% if forloop.first %}
                            {% include 'photo_dropdown.html' %}
                        {% else %}
                            <li role="presentation" id="eventphoto{{photo.id}}">Loading...</li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <form id="story_form" action="{% url 'history:index' %}" method="post">{% csrf_token %}
                    {% include 'form_template.html' %}
                    <input type="submit" value="Post Story"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% if web_articles %}
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">
            {% for news_article in web_articles %}
            <li class="{% if main_id == 0 and  forloop.counter == 1 or main_id == news_article.id %}active{% endif %}"><a href="{% url 'history:article_view' news_article.id %}">{{news_article.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-10">
        <div class="tab-content">
            {% for news_article in web_articles %}
                {% if main_id == 0 and forloop.counter == 1 or main_id == news_article.id %}
                    <div class="tab-pane active" id="{{news_article.id}}">
                        <div class="row">
                        <div class="col-md-9">
                            <h2> {{news_article.title}}</h2>
                            <p>{{news_article.date_posted}}</p>
                            <p>By: <em>{{news_article.created_by.get_firstlast_name}}</em></p>
                            <p class="text-justify">{{news_article.get_full_view|my_markdown}} 
                            </p>
                            <div class="fb-like" data-kid-directed-site="true" data-href="https://tbp.engin.umich.edu{% url 'history:article_view' news_article.id %}" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div><br/>
                        {% url 'history:article_view' news_article.id as the_url %}
                        <div class="g-plusone" data-size="medium" data-href="https://tbp.engin.umich.edu{{ the_url|slice:":-1"}}"></div>
                        <p><a href="https://twitter.com/intent/tweet?screen_name=tbpmig" data-url="https://tbp.engin.umich.edu{% url 'history:article_view' news_article.id %}" data-count="none" class="twitter-mention-button" data-lang="en">Tweet to @tbpmig</a></p>
                            <p>Tagged: {% for member in news_article.tagged_members.all %} 
                                <a href="{% url 'member_resources:profile' member.uniqname %}">{{member}}</a>{% if news_article.tagged_members.count > 2 and not forloop.last %}, {% endif %}{% if news_article.tagged_members.count > 1 and forloop.revcounter == 2 %} and {% endif %}
                            {% endfor %}</p>
                        </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}