electees/urls.py
from django.conf.urls import url

from electees import views


urlpatterns = [
    url(r'^edit_electee_group_membership/$',
        views.edit_electee_group_membership,
        name='edit_electee_group_membership'),
    url(r'^manually_edit_electee_group_membership/$',
        views.manually_edit_electee_group_membership,
        name='manually_edit_electee_group_membership'),
    url(r'^electee_groups/$',
        views.view_electee_groups,
        name='view_electee_groups'),
    url(r'^edit_electee_groups/$',
        views.edit_electee_groups,
        name='edit_electee_groups'),
    url(r'^edit_electee_group_points/$',
        views.edit_electee_group_points,
        name='edit_electee_group_points'),
    url(r'^edit_electee_resources/$',
        views.edit_electee_resources,
        name='edit_electee_resources'),
    url(r'^submit_education_form/$',
        views.submit_background_form,
        name='submit_background_form'),
    url(r'^edit_electee_survey/(?P<term_id>\d+)/$',
        views.edit_survey_for_term,
        name='edit_survey_for_term'),
    url(r'^edit_electee_survey/$',
        views.edit_survey,
        name='edit_survey'),
    url(r'^manage_survey/$',
        views.manage_survey,
        name='manage_survey'),
    url(r'^edit_survey_parts/$',
        views.edit_survey_parts,
        name='edit_survey_parts'),
    url(r'^edit_survey_questions/$',
        views.edit_survey_questions,
        name='edit_survey_questions'),
    url(r'^add_survey_questions_for_term/(?P<term_id>\d+)/$',
        views.add_survey_questions_for_term,
        name='add_survey_questions_for_term'),
    url(r'^add_survey_questions/$',
        views.add_survey_questions,
        name='add_survey_questions'),
    url(r'^preview_survey_for_term/(?P<term_id>\d+)/$',
        views.preview_survey_for_term,
        name='preview_survey_for_term'),
    url(r'^preview_survey/$',
        views.preview_survey,
        name='preview_survey'),
    url(r'^complete_survey_for_term/(?P<term_id>\d+)/$',
        views.complete_survey_for_term,
        name='complete_survey_for_term'),
    url(r'^complete_survey/$',
        views.complete_survey,
        name='complete_survey'),
    url(r'^interview_followup/(?P<interview_id>\d+)/$',
        views.complete_interview_followup,
        name='complete_interview_followup'),
    url(r'^my_interview_forms/$',
        views.view_my_interview_forms,
        name='view_my_interview_forms'),
    url(r'^view_interview_followup/(?P<follow_up_id>\d+)/$',
        views.view_interview_follow_up,
        name='view_interview_follow_up'),
    url(r'^edit_visibility/$',
        views.edit_electee_process_visibility,
        name='edit_electee_process_visibility'),
    url(r'^interview_followup_table/$',
        views.view_interview_follow_up_table,
        name='view_interview_follow_up_table'),   
]

fora/urls.py
from django.conf.urls import url

from fora import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_comment/(?P<forum_id>\d+)-(?P<reply_to_id>\d+)/$',
        views.add_comment, name='add_comment'),
    url(r'^add_thread/(?P<forum_id>\d+)/$',
        views.create_thread, name='create_thread'),
    url(r'^view_thread/(?P<thread_id>\d+)/$',
        views.view_thread, name='view_thread'),
    url(r'^hide_comment/(?P<comment_id>\d+)/$',
        views.hide_comment, name='hide_comment'),
    url(r'^upvote_comment/(?P<comment_id>\d+)/$',
        views.upvote_comment, name='upvote_comment'),
    url(r'^downvote_comment/(?P<comment_id>\d+)/$',
        views.downvote_comment, name='downvote_comment'),
    url(r'^withdraw_upvote/(?P<comment_id>\d+)/$',
        views.withdraw_upvote, name='withdraw_upvote'),
    url(r'^withdraw_downvote/(?P<comment_id>\d+)/$',
        views.withdraw_downvote, name='withdraw_downvote'),
    url(r'^new_forum/$', views.create_forum, name='create_forum'),
    url(r'^delete_forum/(?P<forum_id>\d+)/$',
        views.delete_forum, name='delete_forum'),
    url(r'^get_thread_page/(?P<forum_id>\d+)-(?P<page_num>\d+)/$',
        views.get_thread_page, name='get_thread_page'),
    url(r'^map/$', views.view_map, name='view_map'),
]

member_resources/urls.py
from django.conf.urls import url

from member_resources import views

urlpatterns = [
	url(r'^$',
        views.index, name='index'),
	url(r'^profiles/$',
        views.member_profiles, name='member_profiles'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/$',
        views.profile, name='profile'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/edit/$',
        views.profile_edit, name='profile_edit'),
    url(r'^profiles/create$',
        views.profile_create, name='profile_create'),
    url(r'^progress/(?P<uniqname>[a-z]{3,8})/$',
        views.view_progress,
        name='view_progress'),
    url(r'^track_my_progress/$',
        views.track_my_progress,
        name='track_my_progress'),
    url(r'^edit_progress/(?P<uniqname>[a-z]{3,8})/$',
        views.edit_progress,
        name='edit_progress'),
    url(r'^progress_list/$',
        views.view_progress_list,
        name='view_progress_list'),
    url(r'^progress_table/$',
        views.view_progress_table,
        name='view_progress_table'),
    url(r'^manage_misc_reqs/$',
        views.view_misc_reqs,
        name='view_misc_reqs'),
    url(r'^history_reports/$',
        views.access_history,
        name='access_history'),
    url(r'^approve_tutoring/$',
        views.approve_tutoring_forms,
        name='approve_tutoring_forms'),
    url(r'^electees_stopping_electing/$',
        views.handle_electees_stopping_electing,
        name='handle_electees_stopping_electing'),
    url(r'^manage_active_group_meetings/$',
        views.manage_active_group_meetings,
        name='manage_active_group_meetings'),
    url(r'^manage_project_leaders/$',
        views.manage_project_leaders,
        name='manage_project_leaders'),
    url(r'^add_active_statuses/$',
        views.add_active_statuses,
        name='add_active_statuses'),
    url(r'^add_active_statuses_for_term/(?P<term_id>\d+)/$',
        views.add_active_statuses_for_term,
        name='add_active_statuses_for_term'),
    url(r'^edit_active_statuses/$',
        views.manage_active_statuses,
        name='manage_active_statuses'),
    url(r'^move_electees_to_active/$',
        views.move_electees_to_active,
        name='move_electees_to_active'),
    url(r'^add_electee_DAPA/$',
        views.add_electee_DA_PA_status,
        name='add_electee_DA_PA_status'),
    url(r'^add_leadership_credit/$',
        views.add_leadership_credit,
        name='add_leadership_credit'),
    url(r'^change_requirements/(?P<distinction_id>\d+)/$',
        views.change_requirements,
        name='change_requirements'),
    url(r'^change_event_categories/$',
        views.change_event_categories,
        name='change_event_categories'),
    url(r'^manage_officers/(?P<term_id>\d+)/$',
        views.manage_officers,
        name='manage_officers'),
    url(r'^meeting_feedback/(?P<term_id>\d+)/$',
        views.view_meeting_feedback_for_term,
        name='view_meeting_feedback_for_term'),
    url(r'^meeting_feedback/$',
        views.view_meeting_feedback,
        name='view_meeting_feedback'),
    url(r'^manage_dues/$',
        views.manage_dues,
        name='manage_dues'),
    url(r'^add_actives/$',
        views.add_to_active_list,
        name='add_to_active_list'),
    url(r'^edit_member_lists/$',
        views.edit_list,
        name='edit_list'),
    url(r'^clear_electee_lists/$',
        views.clear_electee_lists,
        name='clear_electee_lists'),
    url(r'^add_ugrad_electees/$',
        views.add_to_ugrad_electee_list,
        name='add_to_ugrad_electee_list'),
    url(r'^add_grad_electees/$',
        views.add_to_grad_electee_list,
        name='add_to_grad_electee_list'),
    url(r'^manage_website/$',
        views.manage_website,
        name='manage_website'),
    url(r'^advance_term/$',
        views.advance_term,
        name='advance_term'),
    url(r'^manage_electee_paperwork/$',
        views.manage_electee_paperwork,
        name='manage_electee_paperwork'),
    url(r'^download_active_progress/$',
        views.download_active_progress,
        name='download_active_progress'),
    url(r'^download_grad_el_progress/$',
        views.download_grad_el_progress,
        name='download_grad_el_progress'),
    url(r'^download_ugrad_el_progress/$',
        views.download_ugrad_el_progress,
        name='download_ugrad_el_progress'),
    url(r'^officer_minutes/$',
        views.officer_meeting_minutes,
        name='officer_meeting_minutes'),
    url(r'^advisory_board_minutes/$',
        views.advisory_board_meeting_minutes,
        name='advisory_board_meeting_minutes'),
    url(r'^meeting_minutes/$',
        views.main_meeting_minutes,
        name='main_meeting_minutes'),
    url(r'^NI_minutes/$',
        views.new_initiatives_meeting_minutes,
        name='new_initiatives_meeting_minutes'),
    url(r'^committee_minutes/$',
        views.committee_meeting_minutes,
        name='committee_meeting_minutes'),
    url(r'^upload_minutes/$',
        views.upload_minutes,
        name='upload_minutes'),
    url(r'^update_preferences/$',
        views.update_preferences,
        name='update_preferences'),
    url(r'^list_project_reports/$',
        views.project_reports_list,
        name='project_reports_list'),
    url(r'^add_external_service/$',
        views.add_external_service,
        name='add_external_service'),
    url(r'^grad_background_forms/$',
        views.view_background_forms,
        name='view_background_forms'),
    url(r'^give_tbpraise/$',
        views.submit_praise,
        name='submit_praise'),
    url(r'^approve_tbpraise/(?P<praise_id>\d+)/$',
        views.approve_praise,
        name='approve_praise'),
    url(r'^new_non_event_project/$',
        views.new_non_event_project,
        name='new_non_event_project'),
    url(r'^non_event_project/(?P<ne_id>\d+)/$',
        views.non_event_project,
        name='non_event_project'),
    url(r'^non_event_project_participants/(?P<ne_id>\d+)/$',
        views.non_event_project_participants,
        name='non_event_project_participants'),
    url(r'^manage_awards/(?P<term_id>\d+)/$',
        views.manage_awards_for_term,
        name='manage_awards_for_term'),
    url(r'^manage_awards/$',
        views.manage_awards,
        name='manage_awards'),
    url(r'^view_electee_surveys/(?P<term_id>\d+)/$',
        views.view_electee_surveys_for_term,
        name='view_electee_surveys_for_term'),
    url(r'^view_electee_surveys/$',
        views.view_electee_surveys,
        name='view_electee_surveys'),
    url(r'^manage_background_checks/$',
        views.add_background_checks,
        name='add_background_checks'),
    url(r'^manage_many_background_checks/$',
        views.mass_add_background_checks,
        name='mass_add_background_checks'),
    url(r'^download_member_data/$',
        views.download_member_data,
        name='download_member_data'),
    url(r'^download_member_data_email/$',
        views.download_member_data_email,
        name='download_member_data_email'),
    url(r'^download_active_status/$',
        views.download_active_status,
        name='download_active_status'),
    url(r'^download_elections_voters/$',
        views.download_elections_voters,
        name='download_elections_voters'),
    url(r'^view_electee_survey/(?P<uniqname>[a-z]{3,8})/$',
        views.view_electee_survey,
        name='view_electee_survey'),
    url(r'^manage_committee_members/(?P<term_id>\d+)/$',
        views.manage_committee_members,
        name='manage_committee_members'),
    url(r'^edit_project_reports/(?P<term_id>\d+)/$',
        views.edit_project_reports,
        name='edit_project_reports'),
    url(r'^manage_committees/$',
        views.manage_committees,
        name='manage_committees'),
    url(r'^view_photos/$',
        views.view_photos,
        name='view_photos'),
    url(r'^manage_alumni_status/$',
        views.manage_alumni_status,
        name='manage_alumni_status'),
]

migweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from migweb import views
from event_cal import views as ev_views
admin.autodiscover()

urlpatterns = [
    url(r'^$',
        views.home, name='home'),
    url(r'^career_fair/companies/$',
        views.cf_companies, name='cf_companies'),
    url(r'^about/',
        include('about.urls', namespace='about')),
    url(r'^outreach/',
        include('outreach.urls', namespace='outreach')),
    url(r'^publications/',
        include('history.urls', namespace='history')),
    url(r'^corporate/',
        include('corporate.urls', namespace='corporate')),
    url(r'^calendar/',
        include('event_cal.urls', namespace='event_cal')),
    url(r'^members/elections/',
        include('elections.urls', namespace='elections')),
    url(r'^members/electees/',
        include('electees.urls', namespace='electees')),
    url(r'^members/playground/',
        include('fora.urls', namespace='fora')),
    # url(r'^bookswap/',
        # include('bookswap.urls', namespace='bookswap')),
    url(r'^members/',
        include('member_resources.urls', namespace='member_resources')),
    #url(r'^admin/plate/', include('django_spaghetti.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', views.login_view, name='login_view'),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'mig_main/login.html'}),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^oauth2callback/$', ev_views.oauth, name='oauth'),
    url(r'^townhalls/$', RedirectView.as_view(url='/outreach/townhalls/')),
    url(r'^pi_day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^pi-day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^piday/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^twitter_oauth/$',
        views.twitter_oauth,
        name='twitter_oauth'),
    url(r'^init_twitter/$',
        views.initialize_twitter,
        name='initialize_twitter'),
    url(r'^slide_ajax/(?P<slide_id>\d+)/$',
        views.get_slide_ajax,
        name='get_slide_ajax'),
    url(r'^photo_ajax/(?P<photo_id>\d+)/$',
        views.get_eventphoto_ajax,
        name='get_eventphoto_ajax'),
    url(r'^article_photo_ajax/(?P<photo_id>\d+)/$',
        views.get_article_photo_ajax,
        name='get_article_photo_ajax'),
    url(r'^select2/', include('django_select2.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

electees/templates/electees/edit_electee_group_membership.html
{% extends "electees/base_electees.html" %}
{% load static %}
{% block subnavEditMembership %}active{%endblock%}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <h4>Update Electee Team Membership </h4>
        <p><a href="{% url 'electees:manually_edit_electee_group_membership' %}" class="btn btn-default">Assign group members manually</a></p>
        <p>Click and drag electees into the desired team and click save to update.</p>
            <h5>Unassigned Electees</h5>
        <div class="DragContainer" id="AllElectees" overclass="OverDragContainer">
            {% for electee in unassigned_electees %}
            <div class="DragBox" id="{{electee.uniqname}}" overclass="OverDragBox" dragclass="DragDragBox">{{electee}}, {% for major in electee.major.all %}{{major.acronym}} {%endfor %}, {{electee.standing}}</div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-6">
        {% for team in electee_groups %}
        <div>
            <h5>{{team.group_name}}</h5>
            <p><strong>Leaders</strong></p>
            <ul>
            {% for leader in team.leaders.all %}
            <li>{{leader.get_firstlast_name}}</li>
            {% endfor %}
            </ul>
            <div class="DragContainer" id="DragContainer{{team.id}}" overclass="OverDragContainer">
                {% for member in team.members.all %}
                <div class="DragBox" id="{{member.uniqname}}" overclass="OverDragBox" dragclass="DragDragBox">{{member}},  {% for major in member.major.all %}{{major.acronym}} {%endfor %}, {{member.standing}}</div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<form action="{% url 'electees:edit_electee_group_membership' %}" method="post" name="electeeGroupMembership">
    {% csrf_token %}
    <p><input type="submit" value="Save Changes" name="submit" id="submitchanges" /></p>
</form>
{% endblock content %}

{% block js %}
<script src="{% static 'js/click_and_drag.js' %}"></script>
<script type="text/javascript">
window.onload = function(){
	// Create our helper object that will show the item while dragging
	dragHelper = document.createElement('DIV');
	dragHelper.style.cssText = 'position:absolute;display:none;';
    CreateDragContainer(
            document.getElementById('AllElectees'),{% for group in electee_groups %}
            document.getElementById('DragContainer{{group.id}}'){% if not forloop.last %},{% endif %}{% endfor %}
	);
	document.body.appendChild(dragHelper);
}
</script>
<script>
    function addHidden(theForm,key,value){
        var input = document.createElement('input');
        input.type = 'hidden';
        input.name = key;
        input.value = value;
        theForm.appendChild(input);
    }
</script>
{% endblock js %}
{% block js_bottom %}
<script type="text/javascript">
    function get_nextsibling(n)
    {
        x = n.nextSibling;
        while (x.nodeType!=1)
        {
            x=x.nextSibling;
        }
        return x
    }
    var theForm = document.forms['electeeGroupMembership'];
    $("#submitchanges").click(function(){
            var datas = {};
            var group_array = [];
            var group_container;
            var electee;
            {% for group in electee_groups %}
            group_array = [];
            group_container = document.getElementById('DragContainer{{group.id}}');
            electee = group_container.firstChild;
            if (electee){
            do{
                if (electee.nodeType == 1){
                    group_array.push(electee.getAttribute('id'));
                }
            }while(electee = electee.nextSibling)
            }
            datas[{{group.id}}]=group_array;
            {% endfor %}
            addHidden(theForm,'electee_groups',JSON.stringify(datas));
            });
</script>
{% endblock %}
{% block css %}
<style type="text/css">
    <!--
    .DragContainer, .OverDragContainer {

        margin: 3px;
        min-width:100px;
        min-height:100px;
        border: #669999 2px solid;
        padding: 5px;
    }
    .DragBox, .OverDragBox, .DragDragBox, .miniDragBox {
        border: #000 1px solid;
        padding: 2px;
        min-width:94px;
        min-height:10px;
        cursor:pointer;
        background-color:#eee;
        margin-bottom:5px;
    }
    .OverDragContainer {
        background-color:#eee;
    }
    .OverDragBox, .DragDragBox {
        background-color:#ffff99;
    }
    .DragDragBox {
        filter: alpha(opacity=50);
        background-color:#ff99cc;
    }
    -->
</style>
{% endblock %}

electees/templates/electees/interview_forms.html
{% extends "electees/base_electees.html" %}

{% block content %}
<div class="row">
    <div class="col-md-12">
    <a class="btn btn-default" href="{% url 'electees:view_electee_groups' %}"><i class="glyphicon glyphicon-chevron-left"></i> To Electee Resources</a>
    <h3>Complete Interview Followup Forms</h3>
    <p>Here are the followup forms for the interviews you've completed or signed up for. Note that you cannot fill out a form until after the interview. Completed forms are marked in green.</p>
    <hr>
    {% for interview in interviews %}
        <p><a href="{% url 'electees:complete_interview_followup' interview.interview.id %}" {% if not interview.enabled %}disabled="disabled"{% endif %} class="btn {% if interview.completed %}btn-success{% else %}btn-primary{%endif%}">
        Fill out followup report for {{interview.interview.interviewer_shift.event.name|slice:":-10"}}, Electee: {% for electee in interview.interview.interviewee_shift.attendees.all %} {{electee}}{% endfor %}
        </a></p>
    {% empty %}
        <p>You are not signed up for any interviews this semester</p>
    {% endfor %}
</div>
{% endblock content %}

electees/templates/electees/manage_survey.html
{% extends "electees/base_electees.html" %}

{% block content %}
<div class="row">
    <div class="col-md-12">
    <h3>Manage Electee Interview Process</h3>
    <hr>
    <a href="{%url 'electees:edit_survey' %}" class="btn {% if survey_exists %}btn-success{% else %}btn-danger{%endif%}">Add/Edit Questionnaire</a>
    <a href="{%url 'electees:edit_survey_parts' %}" class="btn {% if parts_exist %}btn-success{% else %}btn-danger{%endif%}">Add/Edit Questionnaire Parts</a>
    <a href="{%url 'electees:edit_survey_questions' %}" class="btn {% if questions_exist %}btn-success{% else %}btn-danger{%endif%}">Add/Edit Questionnaire Questions</a>
    {% if survey_exists %}
        <a href="{%url 'electees:add_survey_questions' %}" class="btn {% if survey_has_questions %}btn-success{% else %}btn-danger{%endif%}">Add Questions to Questionnaire</a>
        <a href="{%url 'electees:preview_survey' %}" class="btn {% if survey_has_questions %}btn-success{% else %}btn-danger{%endif%}">Preview Questionnaire</a>
    {% else %}
        <a  class="btn btn-danger" disabled="disabled">Add Questions to Questionnaire</a>
        <a  class="btn btn-danger" disabled="disabled">Preview Questionnaire</a>
    {% endif %}
    </div>
    <div class="col-md-12">
        <a href="{%url 'electees:edit_electee_process_visibility' %}" class="btn btn-primary">Update Visibility Settings</a>
    </div>
    
</div>
{% endblock content %}

electees/templates/electees/view_electee_groups.html
{% extends "electees/base_electees.html" %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="row">
        <div class="col-md-12">
        {% if can_edit_resources or can_edit_surveys %}
        <div class="btn-group">
        {% endif %}
        {% if can_edit_resources %}
            <a href="{% url 'electees:edit_electee_resources' %}" class="btn btn-warning">Edit Electee Resources</a>
            <a class="btn btn-warning" href="/media/{{electee_resumes}}"><i class="glyphicon glyphicon-file"></i> Download Electee Resumes</a> 

        {% endif %}
        {% if can_edit_surveys %}
            <a href="{% url 'electees:manage_survey' %}" class="btn btn-warning">Manage Electee Interview Process</a>
        {% endif %}
        {% if can_edit_resources or can_edit_surveys %}
        </div>
        <p></p>
        {% endif %}
        {% if can_complete_surveys or can_submit_background_form or can_submit_interview_followups%}
        <div class="btn-group">
        {% endif %}
        {% if can_complete_surveys %}
            <a href="{% url 'electees:complete_survey' %}" class="btn btn-primary">Electee Questionnaire</a>
        {% endif %}
        {% if can_submit_background_form %}
        <a href="{% url 'electees:submit_background_form' %}" class="btn btn-primary">Educational Background Form</a>
        {% endif %}
        {% if can_submit_interview_followups %}
         <a href="{% url 'electees:view_my_interview_forms' %}" class="btn btn-primary">Submit Interview Follow-ups</a>
        {% endif %}
        {% if can_complete_surveys or can_submit_background_form or can_submit_interview_followups%}
        </div>
        {% endif %}
        {% if can_view_followups %}
        <div class="btn-group">
                <a href="{% url 'electees:view_interview_follow_up_table' %}" class="btn btn-primary">View Interview Followups</a>
        </div>
        {% endif %}
        
        <h3>Electee Resources</h3>
        <h4>Full Packets</h4>
    {% regroup packets|dictsort:"resource_type.id" by resource_type as packets_by_type %}
    {% for resource_type in packets_by_type %}
        <h5>{{resource_type.grouper}}</h5>
        {% for resource in resource_type.list|dictsort:"id"  %}
        <p><a href="{{resource.resource_file.url}}">{{resource}}{% if resource_type.list|length > 1 %} -{{ forloop.counter }}{% endif %}</a></p>
        {% endfor %}
        {% endfor %}
        <hr>
        <h4>Packet Items</h4>
    {% regroup resources|dictsort:"resource_type.id" by resource_type as resources_by_type %}
    {% for resource_type in resources_by_type %}
        <h5>{{resource_type.grouper}}</h5>
        {% for resource in resource_type.list|dictsort:"id"  %}
        <p><a href="{{resource.resource_file.url}}">{{resource}}{% if resource_type.list|length > 1 %} -{{ forloop.counter }}{% endif %}</a></p>
        {% endfor %}
    {% endfor %}
    <hr>
    </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
        <div clas="panel-group" id="past-resources-accordion" role="tablist">
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="collapsed">
                        Past Electee Resources
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body">
                        <h4>Full Packets</h4>
    {% regroup old_packets|dictsort:"resource_type.id" by resource_type as packets_by_type %}
    {% for resource_type in packets_by_type %}
        <h5>{{resource_type.grouper}}</h5>
        {% for resource in resource_type.list|dictsort:"id"  %}
        <p><a href="{{resource.resource_file.url}}">{{resource}}{% if resource_type.list|length > 1 %} -{{ forloop.counter }}{% endif %}</a></p>
        {% endfor %}
        {% endfor %}
        <hr>
        <h4>Packet Items</h4>
    {% regroup old_resources|dictsort:"resource_type.id" by resource_type as resources_by_type %}
    {% for resource_type in resources_by_type %}
        <h5>{{resource_type.grouper}}</h5>
        {% for resource in resource_type.list|dictsort:"id"  %}
        <p><a href="{{resource.resource_file.url}}">{{resource}}{% if resource_type.list|length > 1 %} -{{ forloop.counter }}{% endif %}</a></p>
        {% endfor %}
    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        
        </div>
    </div>
    </div>
    {% if groups|length > 0 %}
    <div class="col-md-4">
        <h3>Electee Teams</h3>
        {% for group in groups|dictsort:"group_name" %}
        <div>
            <h4>{{group.group_name}}</h4>
            <p>Team Leaders</p>
            <ul>
            {% for leader in group.leaders.all %}
                <li><a href="{% url 'member_resources:profile' leader.uniqname %}">{{leader.get_full_name}}</a></li>
            {% endfor %}
            </ul>
            <p>Team Members</p>
            <ul>
            {% for member in group.members.all %}
                <li><a href="{% url 'member_resources:profile' member.uniqname %}">{{member.get_full_name}}</a></li>
            {% endfor %}
            </ul>
        </div>
        <hr/>
        {% endfor %}
    </div>
    <div class="col-md-4">
        <h4>Electee Competition Standings</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Team</th>
                    <th>Points</th>
                </tr>
            </thead>
            <tbody>
            {% regroup groups|dictsortreversed:"points" by points as groups_by_points %}
            {% for point_groups in groups_by_points %}
                {% for group in point_groups.list %}
                    <tr>
                        <td>{% if groups_by_points|length > 1 %}T{% endif %}{{group.get_ranking}}</td>
                        <td>{{group.group_name}}</td>
                        <td>{{point_groups.grouper}}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>
{% endblock content %}