electees/urls.py
from django.conf.urls import url

from electees import views


urlpatterns = [
    url(r'^edit_electee_group_membership/$',
        views.edit_electee_group_membership,
        name='edit_electee_group_membership'),
    url(r'^manually_edit_electee_group_membership/$',
        views.manually_edit_electee_group_membership,
        name='manually_edit_electee_group_membership'),
    url(r'^electee_groups/$',
        views.view_electee_groups,
        name='view_electee_groups'),
    url(r'^edit_electee_groups/$',
        views.edit_electee_groups,
        name='edit_electee_groups'),
    url(r'^edit_electee_group_points/$',
        views.edit_electee_group_points,
        name='edit_electee_group_points'),
    url(r'^edit_electee_resources/$',
        views.edit_electee_resources,
        name='edit_electee_resources'),
    url(r'^submit_education_form/$',
        views.submit_background_form,
        name='submit_background_form'),
    url(r'^edit_electee_survey/(?P<term_id>\d+)/$',
        views.edit_survey_for_term,
        name='edit_survey_for_term'),
    url(r'^edit_electee_survey/$',
        views.edit_survey,
        name='edit_survey'),
    url(r'^manage_survey/$',
        views.manage_survey,
        name='manage_survey'),
    url(r'^edit_survey_parts/$',
        views.edit_survey_parts,
        name='edit_survey_parts'),
    url(r'^edit_survey_questions/$',
        views.edit_survey_questions,
        name='edit_survey_questions'),
    url(r'^add_survey_questions_for_term/(?P<term_id>\d+)/$',
        views.add_survey_questions_for_term,
        name='add_survey_questions_for_term'),
    url(r'^add_survey_questions/$',
        views.add_survey_questions,
        name='add_survey_questions'),
    url(r'^preview_survey_for_term/(?P<term_id>\d+)/$',
        views.preview_survey_for_term,
        name='preview_survey_for_term'),
    url(r'^preview_survey/$',
        views.preview_survey,
        name='preview_survey'),
    url(r'^complete_survey_for_term/(?P<term_id>\d+)/$',
        views.complete_survey_for_term,
        name='complete_survey_for_term'),
    url(r'^complete_survey/$',
        views.complete_survey,
        name='complete_survey'),
    url(r'^interview_followup/(?P<interview_id>\d+)/$',
        views.complete_interview_followup,
        name='complete_interview_followup'),
    url(r'^my_interview_forms/$',
        views.view_my_interview_forms,
        name='view_my_interview_forms'),
    url(r'^view_interview_followup/(?P<follow_up_id>\d+)/$',
        views.view_interview_follow_up,
        name='view_interview_follow_up'),
    url(r'^edit_visibility/$',
        views.edit_electee_process_visibility,
        name='edit_electee_process_visibility'),
    url(r'^interview_followup_table/$',
        views.view_interview_follow_up_table,
        name='view_interview_follow_up_table'),   
]

fora/urls.py
from django.conf.urls import url

from fora import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_comment/(?P<forum_id>\d+)-(?P<reply_to_id>\d+)/$',
        views.add_comment, name='add_comment'),
    url(r'^add_thread/(?P<forum_id>\d+)/$',
        views.create_thread, name='create_thread'),
    url(r'^view_thread/(?P<thread_id>\d+)/$',
        views.view_thread, name='view_thread'),
    url(r'^hide_comment/(?P<comment_id>\d+)/$',
        views.hide_comment, name='hide_comment'),
    url(r'^upvote_comment/(?P<comment_id>\d+)/$',
        views.upvote_comment, name='upvote_comment'),
    url(r'^downvote_comment/(?P<comment_id>\d+)/$',
        views.downvote_comment, name='downvote_comment'),
    url(r'^withdraw_upvote/(?P<comment_id>\d+)/$',
        views.withdraw_upvote, name='withdraw_upvote'),
    url(r'^withdraw_downvote/(?P<comment_id>\d+)/$',
        views.withdraw_downvote, name='withdraw_downvote'),
    url(r'^new_forum/$', views.create_forum, name='create_forum'),
    url(r'^delete_forum/(?P<forum_id>\d+)/$',
        views.delete_forum, name='delete_forum'),
    url(r'^get_thread_page/(?P<forum_id>\d+)-(?P<page_num>\d+)/$',
        views.get_thread_page, name='get_thread_page'),
    url(r'^map/$', views.view_map, name='view_map'),
]

member_resources/urls.py
from django.conf.urls import url

from member_resources import views

urlpatterns = [
	url(r'^$',
        views.index, name='index'),
	url(r'^profiles/$',
        views.member_profiles, name='member_profiles'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/$',
        views.profile, name='profile'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/edit/$',
        views.profile_edit, name='profile_edit'),
    url(r'^profiles/create$',
        views.profile_create, name='profile_create'),
    url(r'^progress/(?P<uniqname>[a-z]{3,8})/$',
        views.view_progress,
        name='view_progress'),
    url(r'^track_my_progress/$',
        views.track_my_progress,
        name='track_my_progress'),
    url(r'^edit_progress/(?P<uniqname>[a-z]{3,8})/$',
        views.edit_progress,
        name='edit_progress'),
    url(r'^progress_list/$',
        views.view_progress_list,
        name='view_progress_list'),
    url(r'^progress_table/$',
        views.view_progress_table,
        name='view_progress_table'),
    url(r'^manage_misc_reqs/$',
        views.view_misc_reqs,
        name='view_misc_reqs'),
    url(r'^history_reports/$',
        views.access_history,
        name='access_history'),
    url(r'^approve_tutoring/$',
        views.approve_tutoring_forms,
        name='approve_tutoring_forms'),
    url(r'^electees_stopping_electing/$',
        views.handle_electees_stopping_electing,
        name='handle_electees_stopping_electing'),
    url(r'^manage_active_group_meetings/$',
        views.manage_active_group_meetings,
        name='manage_active_group_meetings'),
    url(r'^manage_project_leaders/$',
        views.manage_project_leaders,
        name='manage_project_leaders'),
    url(r'^add_active_statuses/$',
        views.add_active_statuses,
        name='add_active_statuses'),
    url(r'^add_active_statuses_for_term/(?P<term_id>\d+)/$',
        views.add_active_statuses_for_term,
        name='add_active_statuses_for_term'),
    url(r'^edit_active_statuses/$',
        views.manage_active_statuses,
        name='manage_active_statuses'),
    url(r'^move_electees_to_active/$',
        views.move_electees_to_active,
        name='move_electees_to_active'),
    url(r'^add_electee_DAPA/$',
        views.add_electee_DA_PA_status,
        name='add_electee_DA_PA_status'),
    url(r'^add_leadership_credit/$',
        views.add_leadership_credit,
        name='add_leadership_credit'),
    url(r'^change_requirements/(?P<distinction_id>\d+)/$',
        views.change_requirements,
        name='change_requirements'),
    url(r'^change_event_categories/$',
        views.change_event_categories,
        name='change_event_categories'),
    url(r'^manage_officers/(?P<term_id>\d+)/$',
        views.manage_officers,
        name='manage_officers'),
    url(r'^meeting_feedback/(?P<term_id>\d+)/$',
        views.view_meeting_feedback_for_term,
        name='view_meeting_feedback_for_term'),
    url(r'^meeting_feedback/$',
        views.view_meeting_feedback,
        name='view_meeting_feedback'),
    url(r'^manage_dues/$',
        views.manage_dues,
        name='manage_dues'),
    url(r'^add_actives/$',
        views.add_to_active_list,
        name='add_to_active_list'),
    url(r'^edit_member_lists/$',
        views.edit_list,
        name='edit_list'),
    url(r'^clear_electee_lists/$',
        views.clear_electee_lists,
        name='clear_electee_lists'),
    url(r'^add_ugrad_electees/$',
        views.add_to_ugrad_electee_list,
        name='add_to_ugrad_electee_list'),
    url(r'^add_grad_electees/$',
        views.add_to_grad_electee_list,
        name='add_to_grad_electee_list'),
    url(r'^manage_website/$',
        views.manage_website,
        name='manage_website'),
    url(r'^advance_term/$',
        views.advance_term,
        name='advance_term'),
    url(r'^manage_electee_paperwork/$',
        views.manage_electee_paperwork,
        name='manage_electee_paperwork'),
    url(r'^download_active_progress/$',
        views.download_active_progress,
        name='download_active_progress'),
    url(r'^download_grad_el_progress/$',
        views.download_grad_el_progress,
        name='download_grad_el_progress'),
    url(r'^download_ugrad_el_progress/$',
        views.download_ugrad_el_progress,
        name='download_ugrad_el_progress'),
    url(r'^officer_minutes/$',
        views.officer_meeting_minutes,
        name='officer_meeting_minutes'),
    url(r'^advisory_board_minutes/$',
        views.advisory_board_meeting_minutes,
        name='advisory_board_meeting_minutes'),
    url(r'^meeting_minutes/$',
        views.main_meeting_minutes,
        name='main_meeting_minutes'),
    url(r'^NI_minutes/$',
        views.new_initiatives_meeting_minutes,
        name='new_initiatives_meeting_minutes'),
    url(r'^committee_minutes/$',
        views.committee_meeting_minutes,
        name='committee_meeting_minutes'),
    url(r'^upload_minutes/$',
        views.upload_minutes,
        name='upload_minutes'),
    url(r'^update_preferences/$',
        views.update_preferences,
        name='update_preferences'),
    url(r'^list_project_reports/$',
        views.project_reports_list,
        name='project_reports_list'),
    url(r'^add_external_service/$',
        views.add_external_service,
        name='add_external_service'),
    url(r'^grad_background_forms/$',
        views.view_background_forms,
        name='view_background_forms'),
    url(r'^give_tbpraise/$',
        views.submit_praise,
        name='submit_praise'),
    url(r'^approve_tbpraise/(?P<praise_id>\d+)/$',
        views.approve_praise,
        name='approve_praise'),
    url(r'^new_non_event_project/$',
        views.new_non_event_project,
        name='new_non_event_project'),
    url(r'^non_event_project/(?P<ne_id>\d+)/$',
        views.non_event_project,
        name='non_event_project'),
    url(r'^non_event_project_participants/(?P<ne_id>\d+)/$',
        views.non_event_project_participants,
        name='non_event_project_participants'),
    url(r'^manage_awards/(?P<term_id>\d+)/$',
        views.manage_awards_for_term,
        name='manage_awards_for_term'),
    url(r'^manage_awards/$',
        views.manage_awards,
        name='manage_awards'),
    url(r'^view_electee_surveys/(?P<term_id>\d+)/$',
        views.view_electee_surveys_for_term,
        name='view_electee_surveys_for_term'),
    url(r'^view_electee_surveys/$',
        views.view_electee_surveys,
        name='view_electee_surveys'),
    url(r'^manage_background_checks/$',
        views.add_background_checks,
        name='add_background_checks'),
    url(r'^manage_many_background_checks/$',
        views.mass_add_background_checks,
        name='mass_add_background_checks'),
    url(r'^download_member_data/$',
        views.download_member_data,
        name='download_member_data'),
    url(r'^download_member_data_email/$',
        views.download_member_data_email,
        name='download_member_data_email'),
    url(r'^download_active_status/$',
        views.download_active_status,
        name='download_active_status'),
    url(r'^download_elections_voters/$',
        views.download_elections_voters,
        name='download_elections_voters'),
    url(r'^view_electee_survey/(?P<uniqname>[a-z]{3,8})/$',
        views.view_electee_survey,
        name='view_electee_survey'),
    url(r'^manage_committee_members/(?P<term_id>\d+)/$',
        views.manage_committee_members,
        name='manage_committee_members'),
    url(r'^edit_project_reports/(?P<term_id>\d+)/$',
        views.edit_project_reports,
        name='edit_project_reports'),
    url(r'^manage_committees/$',
        views.manage_committees,
        name='manage_committees'),
    url(r'^view_photos/$',
        views.view_photos,
        name='view_photos'),
    url(r'^manage_alumni_status/$',
        views.manage_alumni_status,
        name='manage_alumni_status'),
]

migweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from migweb import views
from event_cal import views as ev_views
admin.autodiscover()

urlpatterns = [
    url(r'^$',
        views.home, name='home'),
    url(r'^career_fair/companies/$',
        views.cf_companies, name='cf_companies'),
    url(r'^about/',
        include('about.urls', namespace='about')),
    url(r'^outreach/',
        include('outreach.urls', namespace='outreach')),
    url(r'^publications/',
        include('history.urls', namespace='history')),
    url(r'^corporate/',
        include('corporate.urls', namespace='corporate')),
    url(r'^calendar/',
        include('event_cal.urls', namespace='event_cal')),
    url(r'^members/elections/',
        include('elections.urls', namespace='elections')),
    url(r'^members/electees/',
        include('electees.urls', namespace='electees')),
    url(r'^members/playground/',
        include('fora.urls', namespace='fora')),
    # url(r'^bookswap/',
        # include('bookswap.urls', namespace='bookswap')),
    url(r'^members/',
        include('member_resources.urls', namespace='member_resources')),
    #url(r'^admin/plate/', include('django_spaghetti.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', views.login_view, name='login_view'),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'mig_main/login.html'}),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^oauth2callback/$', ev_views.oauth, name='oauth'),
    url(r'^townhalls/$', RedirectView.as_view(url='/outreach/townhalls/')),
    url(r'^pi_day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^pi-day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^piday/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^twitter_oauth/$',
        views.twitter_oauth,
        name='twitter_oauth'),
    url(r'^init_twitter/$',
        views.initialize_twitter,
        name='initialize_twitter'),
    url(r'^slide_ajax/(?P<slide_id>\d+)/$',
        views.get_slide_ajax,
        name='get_slide_ajax'),
    url(r'^photo_ajax/(?P<photo_id>\d+)/$',
        views.get_eventphoto_ajax,
        name='get_eventphoto_ajax'),
    url(r'^article_photo_ajax/(?P<photo_id>\d+)/$',
        views.get_article_photo_ajax,
        name='get_article_photo_ajax'),
    url(r'^select2/', include('django_select2.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member_resources/models.py
from django.db import models

from django.core.validators import RegexValidator
# Create your models here

class MemberList(models.Model):
    class Meta:
        abstract = True

    uniqname = models.CharField(max_length=8,
                                validators =[RegexValidator(regex=r'^[a-z]{3,8}$',
                                message="Uniqnames must be 3-8 characters, all letters")])
    def __unicode__(self):
        return self.uniqname
                                
class ActiveList(MemberList):
    pass

class GradElecteeList(MemberList):
    pass
    
class UndergradElecteeList(MemberList):
    pass

class ProjectLeaderList(models.Model):
    member_profile = models.ForeignKey('mig_main.MemberProfile')

member_resources/forms.py
from django.forms import ModelForm, Form
from django import forms
from django.forms.formsets import formset_factory, BaseFormSet
from django.forms.models import modelformset_factory
from django.db.models import Q


from django_select2.forms import Select2Widget

from electees.models import ElecteeGroup
from member_resources.models import ProjectLeaderList
from mig_main.models import MemberProfile, UserProfile, TBPraise
from history.models import Distinction
from requirements.models import (
                ProgressItem,
                DistinctionType,
)


class MassAddForm(Form):
    uniqnames = forms.CharField(widget=forms.Textarea)


class ManageProjectLeaderForm(ModelForm):
    member_profile = forms.ModelChoiceField(
                        widget=Select2Widget(),
                        queryset=MemberProfile.get_members()
    )

    class Meta:
        model = ProjectLeaderList
        fields = ['member_profile']


ManageProjectLeadersFormSet = modelformset_factory(
                                    ProjectLeaderList,
                                    form=ManageProjectLeaderForm,
                                    extra=3,
                                    can_delete=True
)


class ExternalServiceForm(forms.ModelForm):
    member = forms.ModelChoiceField(
                        widget=Select2Widget(),
                        queryset=MemberProfile.get_electees()
    )

    class Meta:
        model = ProgressItem
        exclude = ('term', 'date_completed', 'event_type', 'related_event')


class TBPraiseForm(forms.ModelForm):
    recipient = forms.ModelChoiceField(
                    widget=Select2Widget(),
                    queryset=UserProfile.get_users()
    )

    class Meta:
        model = TBPraise
        exclude = ('giver', 'date_added', 'approved')

member_resources/templates/member_resources/generic_form.html
{% extends "member_resources/base_member_resources.html" %}
{% load staticfiles %}
{% if dp_ids %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/datepicker.css' %}" />
{% endblock css %}
{% block js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
{% include 'datepicker.html' %}
{% endblock %}
{% endif %}
{% block content %}
{% if back_button %}
<div class = "row-fluid">
    <div class="span4">
        <p><a class="btn" href="{{back_button.link}}"><i class="icon-chevron-left"></i> {{back_button.text}}</a></p>
    </div>
</div>
{% endif %}
<div class="row-fluid">
    <div class="span6">
        <h4>{{form_title}}</h4>
        <p>{{help_text}}</p>
        <form {% if has_files %}enctype="multipart/form-data"{% endif %} action="{{request.path}}" method="post">{% csrf_token %}
            {% include 'form_template.html' %}
            <input type="submit" value="{{submit_name}}"/>
        </form>
    </div>
</div>
{% endblock %}

{% if extra_js %}
{% block js_bottom %}
{% for html_file in extra_js %}
{% include html_file %}
{% endfor %}
{% endblock %}
{% endif %}

member_resources/templates/member_resources/manage_misc_reqs.html
{% extends "member_resources/base_member_resources.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h3>Requirement Management</h3>
        <p>This section is for managing members' progress toward requirements (paperwork, dues, electee exams, etc.) and also for updating the requirements themselves</p>
        <p>The items you have permission to manage are listed below.</p>
        {% if can_change_requirements %}
        <h4>Update/Change Requirements</h4>
        <ul>
            {% if can_change_active_reqs %}
            <li><a href="{% url 'member_resources:change_event_categories' %}">Change Event Categories</a></li>
            {% for distinction in active_distinctions %}
            <li><a href="{% url 'member_resources:change_requirements' distinction.id %}">Update {{distinction.name}} Requirements</a></li>
            {% endfor %}
        {% endif %}
        {% if can_change_ugrad_electee_reqs %}
            {% for distinction in ugrad_electee_distinctions %}
            <li><a href="{% url 'member_resources:change_requirements' distinction.id %}">Update {{distinction.name}} Requirements</a></li>
            {% endfor %}
        {% endif %}
        {% if can_change_grad_electee_reqs %}
            {% for distinction in grad_electee_distinctions %}
            <li><a href="{% url 'member_resources:change_requirements' distinction.id %}">Update {{distinction.name}} Requirements</a></li>
            {% endfor %}
        {% endif %}
        </ul>
        {% endif %}
        {% if can_manage_misc_reqs %}
        <h4>Manage Members' Progress toward Requirements</h4>
        <ul>
        {% if can_add_leadership_credit %}
            <li><a href="{% url 'member_resources:add_leadership_credit' %}">Add Leadership Credits</a></li>
        {% endif %}
        {% if can_manage_finances %}
            <li><a href="{% url 'member_resources:manage_dues' %}">Manage Dues Payment</a></li>
        {% endif %}
        {% if can_approve_tutoring %}
            <li><a href="{% url 'member_resources:approve_tutoring_forms' %}">Approve Tutoring Forms</a></li>
        {% endif %}
        {% if can_add_external_service %}
            <li><a href="{% url 'member_resources:add_external_service' %}">Add External Service Hours</a></li>
        {% endif %}
        {% if can_manage_electee_paperwork %}
            <li><a href="{% url 'member_resources:manage_electee_paperwork' %}">Manage Electee Paperwork</a></li>
        {% endif %}
        {% if can_manage_interviews %}
            <li><a href="{% url 'member_resources:manage_active_group_meetings' %}">Manage Active's Electee Team Meeting Attendance</a></li>
        {% endif %}

        </ul>
        {% endif %}
    </div>
    <hr class="hidden-md hidden-lg">
    <div class="col-md-6">
        <h3>Membership Management</h3>
        <p>This section is for managing the membership profiles/permissions.</p>
        <p>The items you have permission to manage are listed below.</p>
        <ul>
        {% if can_add_electee_members %}
        <li><a href="{% url 'member_resources:add_to_ugrad_electee_list' %}">Add New Undergrad Electees</a></li>
        <li><a href="{% url 'member_resources:add_to_grad_electee_list' %}">Add New Grad Electees</a></li>
        <li><a href="{% url 'member_resources:edit_list' %}">Edit List of Potential Electees</a></li>
        {% endif %}
        {% if can_manage_electees %}
            <li><a href="{% url 'member_resources:move_electees_to_active' %}">Move Electees To Actives</a></li>
            <li><a href="{% url 'member_resources:handle_electees_stopping_electing' %}">Update Electees Stopping Electing</a></li>
        {% endif %}
        {% if can_manage_project_leaders %}
            <li><a href="{% url 'member_resources:manage_project_leaders' %}">Manage Project Leaders</a></li>
        {% endif %}
        {% if can_manage_actives %}
            <li><a href="{% url 'member_resources:add_to_active_list' %}">Add Active Members</a></li>
            <li><a href="{% url 'member_resources:add_active_statuses' %}">Add Active/DA/PA Status for current term</a></li>
            <li><a href="{% url 'member_resources:manage_active_statuses' %}">Edit/Remove Active/DA/PA Status</a></li>
            <li><a href="{% url 'member_resources:add_electee_DA_PA_status' %}">Add Electee DA/PA Status</a></li>
            <li><a href="{% url 'member_resources:manage_alumni_status' %}">Move Graduates to Alumni</a></li>
        {% endif %}
        {% if can_manage_background_checks %}
            <li><a href="{% url 'member_resources:add_background_checks' %}">Add Background Checks</a></li>
            <li><a href="{% url 'member_resources:mass_add_background_checks' %}">Add Many Background Checks</a></li>
        {% endif %}
        {% if can_manage_committees %}
        <li><a href="{% url 'member_resources:manage_committee_members' current_term.id%}">Manage Committee Members for Current Term</a></li>
        {% endif %}
        {% if can_manage_officers %}
        <li><a href="{% url 'member_resources:manage_committees' %}">Manage Committees</a></li>
        <li><a href="{% url 'member_resources:manage_officers' current_term.id%}">Manage Officers for Current Term</a></li>
        <li><a href="{% url 'member_resources:manage_officers' next_term.id%}">Manage Officers for Next Term</a></li>
    </ul>
        <div class="panel-group" id="allterms">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#allterms" href="#allTermsOpen">
                            Manage Officers for Other Terms
                        </a>
                    </h4>
                </div>
                <div id="allTermsOpen" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
        {% for term in terms %}
        <li><a href="{% url 'member_resources:manage_officers' term.id%}">Manage Officers for {{term}} Term</a></li>
        {% endfor %}</ul>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        </ul>
        {% if can_view_demographics or can_manage_actives or can_download_active_status %}
        <h3>Member Demographics</h3>
        <ul>
        {% if can_view_demographics %}
             <li><a href="{% url 'member_resources:download_member_data' %}">Download COE Member Data</a></li>
         {% endif %}
         {% if can_download_active_status %}
             <li><a href="{% url 'member_resources:download_active_status' %}">Download Active Status Data</a></li>
             <li><a href="{% url 'member_resources:download_elections_voters' %}">Download Active/Electee Status for Elections</a></li>
        {% endif %}
        {% if can_manage_actives %}
            <li><a href="{% url 'member_resources:download_member_data_email' %}">Download Member Data for Email Lists</a></li>
        {% endif %}
        </ul>
        {% endif %}
    </div>
    
    
</div>
{% endblock content %}

member_resources/templates/member_resources/manage_reports.html
{% extends "member_resources/base_member_resources.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h3>History/Report Management</h3>
        <p>This page is for managing/viewing history/reports.</p>
        <p>The items you have permission to manage are listed below.</p>
        <ul>
        {% if can_view_feedback %}
            <li><a href="{% url 'member_resources:view_meeting_feedback' %}">View Meeting Feedback</a></li>
        {% endif %}
        {% if can_access_project_reports %}
            <li><a href="{% url 'member_resources:project_reports_list' %}">View Project Reports</a></li>
        {% endif %}
        {% if can_create_nep %}
            <li><a href="{% url 'member_resources:new_non_event_project' %}">Create New Non-Event Project and Report</a></li>
        {% endif %}
        {% if can_add_awards %}
            <li><a href="{% url 'member_resources:manage_awards' %}">Manage Awards</a></li>
        {% endif %}
            <li><a href="{% url 'member_resources:main_meeting_minutes' %}">View Meeting Minutes</a></li>
        {% if can_view_surveys %}
            <li><a href="{% url 'member_resources:view_electee_surveys' %}">View Electee Surveys</a></li>
        {% endif %}
        </ul>
    </div>
</div>
{% endblock content %}

member_resources/templates/member_resources/manage_website.html
{% extends "member_resources/base_member_resources.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        <h4>Manage Website Settings</h4>
        {% if can_change_term %}
        <a class="btn btn-default" href="{% url 'member_resources:advance_term' %}">Change Website Term from {{term}} to {{next_term}}</a>{% if warn_about_change %}
        <p class ="text-warning">Note, it is not currently the usual time to change the website term. Proceed with caution as this will have effects on user progress, officer permissions, and interactability</p>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-md-9">
        <h3>Manage Homepage Slideshow</h3>
        <p>For local links, do not include the domain. For external links http/https <b>must</b> be included.</p>
<form enctype="multipart/form-data" method="post" action="{% url 'member_resources:manage_website'%}">
    {% csrf_token %}
    {{ formset.management_form }}
    <table class="table table-striped">
        {% include 'formset_template.html' %}
    </table>
    <p><a class="btn btn-default add-row"  href="javascript:void(0)"/>Add another photo</a></p>
    <input type="submit" value="Update Slideshow Photos" name = "submit"/>
</div>
</form>
</div>
{% endblock content %}

member_resources/templates/member_resources/member_list.html
{% if members %}

    <div class="col-sm-6">
        <h4>{{member_type}}</h4>
        
        {% regroup members|dictsort:"standing.id" by standing as profiles_by_standing %}
        <div class="row">
    {% for standing in profiles_by_standing %}
        <div class="col-md-4">
            <h5>{{standing.grouper}}</h5>
            {% for profile in standing.list|dictsort:"last_name" %}
                <p><a href="{% url 'member_resources:profile' profile.uniqname %}">{{profile.get_full_name}}</a></p>
            {% endfor %}
            <hr class="hidden-md hidden-lg"/>
        </div>
    {% endfor %}
        </div>
    </div>
{% endif %}