event_cal/urls.py
from django.conf.urls import url

from event_cal import views

urlpatterns = [
	url(r'^$',
        views.index, name='index'),
	url(r'^event_list/$',
        views.list,
        name='list'),
	url(r'^calendar_admin/$',
        views.calendar_admin,
        name='calendar_admin'),
	url(r'^generate_announcements/$',
        views.generate_announcements,
        name='generate_announcements'),
	url(r'^edit_announcements/$',
        views.edit_announcements,
        name='edit_announcements'),
	url(r'^add_announcement/$',
        views.add_announcement,
        name='add_announcement'),
	url(r'^tutoring_form/$',
        views.submit_tutoring_form,
        name='submit_tutoring_form'),
	url(r'^my_events/$',
        views.my_events,
        name='my_events'),
    url(r'^create_event/$',
        views.create_event,
        name='create_event'),
    url(r'^create_multishift_event/$',
        views.create_multishift_event,
        name='create_multishift_event'),
    url(r'^create_interviews/$',
        views.create_electee_interviews,
        name='create_electee_interviews'),
    url(r'^add_event_photo/$',
        views.add_event_photo,
        name='add_event_photo'),
    url(r'^create_meeting_signin/(?P<event_id>\d+)/$',
        views.create_meeting_signin,
        name='create_meeting_signin'),
    url(r'^delete_event/(?P<event_id>\d+)/$',
        views.delete_event,
        name='delete_event'),
    url(r'^email_event_participants/(?P<event_id>\d+)/$',
        views.email_participants,
        name='email_participants'),
    url(r'^event_project_report/(?P<event_id>\d+)/$',
        views.event_project_report,
        name='event_project_report'),
    url(r'^misc_project_report/(?P<ne_id>\d+)/$',
        views.non_event_project_report,
        name='non_event_project_report'),
    url(r'^project_report_by_id/(?P<report_id>\d+)/$',
        views.project_report_by_id,
        name='project_report_by_id'),
    url(r'^edit_event/(?P<event_id>\d+)/$',
        views.edit_event, name='edit_event'),
    url(r'^carpool_sign_up/(?P<event_id>\d+)/$',
        views.carpool_sign_up, name='carpool_sign_up'),
    url(r'^preferred_items_request/(?P<event_id>\d+)/$',
        views.preferred_items_request, name='preferred_items_request'),
    url(r'^complete_event/(?P<event_id>\d+)/$',
        views.complete_event, name='complete_event'),
    url(r'^update_event/(?P<event_id>\d+)/$',
        views.update_completed_event, name='update_completed_event'),
    url(r'^delete_shift/(?P<shift_id>\d+)/$',
        views.delete_shift, name='delete_shift'),
    url(r'event/(?P<event_id>\d+)/$',
        views.event_detail, name='event_detail'),
    url(r'event_table_view/(?P<event_id>\d+)/$',
        views.event_detail_table, name='event_detail_table'),
    url(r'interview_view_electees/(?P<event_id>\d+)/$',
        views.interview_view_electees, name='interview_view_electees'),
    url(r'interview_view_actives/(?P<event_id>\d+)/$',
        views.interview_view_actives, name='interview_view_actives'),
    # don't change this order-- YAY regex!\
    url(r'unsign_up_paired/(?P<shift_id>\d+)/$',
        views.unsign_up_paired, name='unsign_up_paired'),
    url(r'sign_up_paired/(?P<shift_id>\d+)/$',
        views.sign_up_paired, name='sign_up_paired'),
    url(r'unsign_up/(?P<shift_id>\d+)/$',
        views.unsign_up, name='unsign_up'),
    url(r'sign_up/(?P<shift_id>\d+)/$',
        views.sign_up, name='sign_up'),
    url(r'add_gcal_paired/(?P<shift_id>\d+)/$',
        views.add_shift_to_gcal_paired, name='add_shift_to_gcal_paired'),
    url(r'add_gcal/(?P<shift_id>\d+)/$',
        views.add_shift_to_gcal, name='add_shift_to_gcal'),
    url(r'remove_user_from_paired_shift/(?P<shift_id>\d+)-(?P<username>[a-z]{3,8})/$',
        views.manual_remove_user_from_paired_shift,
        name='manual_remove_user_from_paired_shift'),
    url(r'remove_user_from_shift/(?P<shift_id>\d+)-(?P<username>[a-z]{3,8})/$',
        views.manual_remove_user_from_shift,
        name='manual_remove_user_from_shift'),
    url(r'add_to_waitlist/(?P<shift_id>\d+)/$',
        views.add_to_waitlist, name='add_to_waitlist'),
    url(r'remove_from_waitlist/(?P<shift_id>\d+)/$',
        views.remove_from_waitlist, name='remove_from_waitlist'),
    url(r'meeting_sign_in/(?P<shift_id>\d+)/$',
        views.meeting_sign_in, name='meeting_sign_in'),
    url(r'authorize_google_cal/',
        views.gcal_test,name='gcal_test'),
    url(r'^event_attach_report/(?P<event_id>\d+)/$',
        views.add_project_report_to_event, name='add_project_report_to_event'),
    url(r'^event_ajax/(?P<event_id>\d+)/$',
        views.get_event_ajax,name='get_event_ajax'),

]

fora/urls.py
from django.conf.urls import url

from fora import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_comment/(?P<forum_id>\d+)-(?P<reply_to_id>\d+)/$',
        views.add_comment, name='add_comment'),
    url(r'^add_thread/(?P<forum_id>\d+)/$',
        views.create_thread, name='create_thread'),
    url(r'^view_thread/(?P<thread_id>\d+)/$',
        views.view_thread, name='view_thread'),
    url(r'^hide_comment/(?P<comment_id>\d+)/$',
        views.hide_comment, name='hide_comment'),
    url(r'^upvote_comment/(?P<comment_id>\d+)/$',
        views.upvote_comment, name='upvote_comment'),
    url(r'^downvote_comment/(?P<comment_id>\d+)/$',
        views.downvote_comment, name='downvote_comment'),
    url(r'^withdraw_upvote/(?P<comment_id>\d+)/$',
        views.withdraw_upvote, name='withdraw_upvote'),
    url(r'^withdraw_downvote/(?P<comment_id>\d+)/$',
        views.withdraw_downvote, name='withdraw_downvote'),
    url(r'^new_forum/$', views.create_forum, name='create_forum'),
    url(r'^delete_forum/(?P<forum_id>\d+)/$',
        views.delete_forum, name='delete_forum'),
    url(r'^get_thread_page/(?P<forum_id>\d+)-(?P<page_num>\d+)/$',
        views.get_thread_page, name='get_thread_page'),
    url(r'^map/$', views.view_map, name='view_map'),
]

member_resources/urls.py
from django.conf.urls import url

from member_resources import views

urlpatterns = [
	url(r'^$',
        views.index, name='index'),
	url(r'^profiles/$',
        views.member_profiles, name='member_profiles'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/$',
        views.profile, name='profile'),
	url(r'^profiles/(?P<uniqname>[a-z]{3,8})/edit/$',
        views.profile_edit, name='profile_edit'),
    url(r'^profiles/create$',
        views.profile_create, name='profile_create'),
    url(r'^progress/(?P<uniqname>[a-z]{3,8})/$',
        views.view_progress,
        name='view_progress'),
    url(r'^track_my_progress/$',
        views.track_my_progress,
        name='track_my_progress'),
    url(r'^edit_progress/(?P<uniqname>[a-z]{3,8})/$',
        views.edit_progress,
        name='edit_progress'),
    url(r'^progress_list/$',
        views.view_progress_list,
        name='view_progress_list'),
    url(r'^progress_table/$',
        views.view_progress_table,
        name='view_progress_table'),
    url(r'^manage_misc_reqs/$',
        views.view_misc_reqs,
        name='view_misc_reqs'),
    url(r'^history_reports/$',
        views.access_history,
        name='access_history'),
    url(r'^approve_tutoring/$',
        views.approve_tutoring_forms,
        name='approve_tutoring_forms'),
    url(r'^electees_stopping_electing/$',
        views.handle_electees_stopping_electing,
        name='handle_electees_stopping_electing'),
    url(r'^manage_active_group_meetings/$',
        views.manage_active_group_meetings,
        name='manage_active_group_meetings'),
    url(r'^manage_project_leaders/$',
        views.manage_project_leaders,
        name='manage_project_leaders'),
    url(r'^add_active_statuses/$',
        views.add_active_statuses,
        name='add_active_statuses'),
    url(r'^add_active_statuses_for_term/(?P<term_id>\d+)/$',
        views.add_active_statuses_for_term,
        name='add_active_statuses_for_term'),
    url(r'^edit_active_statuses/$',
        views.manage_active_statuses,
        name='manage_active_statuses'),
    url(r'^move_electees_to_active/$',
        views.move_electees_to_active,
        name='move_electees_to_active'),
    url(r'^add_electee_DAPA/$',
        views.add_electee_DA_PA_status,
        name='add_electee_DA_PA_status'),
    url(r'^add_leadership_credit/$',
        views.add_leadership_credit,
        name='add_leadership_credit'),
    url(r'^change_requirements/(?P<distinction_id>\d+)/$',
        views.change_requirements,
        name='change_requirements'),
    url(r'^change_event_categories/$',
        views.change_event_categories,
        name='change_event_categories'),
    url(r'^manage_officers/(?P<term_id>\d+)/$',
        views.manage_officers,
        name='manage_officers'),
    url(r'^meeting_feedback/(?P<term_id>\d+)/$',
        views.view_meeting_feedback_for_term,
        name='view_meeting_feedback_for_term'),
    url(r'^meeting_feedback/$',
        views.view_meeting_feedback,
        name='view_meeting_feedback'),
    url(r'^manage_dues/$',
        views.manage_dues,
        name='manage_dues'),
    url(r'^add_actives/$',
        views.add_to_active_list,
        name='add_to_active_list'),
    url(r'^edit_member_lists/$',
        views.edit_list,
        name='edit_list'),
    url(r'^clear_electee_lists/$',
        views.clear_electee_lists,
        name='clear_electee_lists'),
    url(r'^add_ugrad_electees/$',
        views.add_to_ugrad_electee_list,
        name='add_to_ugrad_electee_list'),
    url(r'^add_grad_electees/$',
        views.add_to_grad_electee_list,
        name='add_to_grad_electee_list'),
    url(r'^manage_website/$',
        views.manage_website,
        name='manage_website'),
    url(r'^advance_term/$',
        views.advance_term,
        name='advance_term'),
    url(r'^manage_electee_paperwork/$',
        views.manage_electee_paperwork,
        name='manage_electee_paperwork'),
    url(r'^download_active_progress/$',
        views.download_active_progress,
        name='download_active_progress'),
    url(r'^download_grad_el_progress/$',
        views.download_grad_el_progress,
        name='download_grad_el_progress'),
    url(r'^download_ugrad_el_progress/$',
        views.download_ugrad_el_progress,
        name='download_ugrad_el_progress'),
    url(r'^officer_minutes/$',
        views.officer_meeting_minutes,
        name='officer_meeting_minutes'),
    url(r'^advisory_board_minutes/$',
        views.advisory_board_meeting_minutes,
        name='advisory_board_meeting_minutes'),
    url(r'^meeting_minutes/$',
        views.main_meeting_minutes,
        name='main_meeting_minutes'),
    url(r'^NI_minutes/$',
        views.new_initiatives_meeting_minutes,
        name='new_initiatives_meeting_minutes'),
    url(r'^committee_minutes/$',
        views.committee_meeting_minutes,
        name='committee_meeting_minutes'),
    url(r'^upload_minutes/$',
        views.upload_minutes,
        name='upload_minutes'),
    url(r'^update_preferences/$',
        views.update_preferences,
        name='update_preferences'),
    url(r'^list_project_reports/$',
        views.project_reports_list,
        name='project_reports_list'),
    url(r'^add_external_service/$',
        views.add_external_service,
        name='add_external_service'),
    url(r'^grad_background_forms/$',
        views.view_background_forms,
        name='view_background_forms'),
    url(r'^give_tbpraise/$',
        views.submit_praise,
        name='submit_praise'),
    url(r'^approve_tbpraise/(?P<praise_id>\d+)/$',
        views.approve_praise,
        name='approve_praise'),
    url(r'^new_non_event_project/$',
        views.new_non_event_project,
        name='new_non_event_project'),
    url(r'^non_event_project/(?P<ne_id>\d+)/$',
        views.non_event_project,
        name='non_event_project'),
    url(r'^non_event_project_participants/(?P<ne_id>\d+)/$',
        views.non_event_project_participants,
        name='non_event_project_participants'),
    url(r'^manage_awards/(?P<term_id>\d+)/$',
        views.manage_awards_for_term,
        name='manage_awards_for_term'),
    url(r'^manage_awards/$',
        views.manage_awards,
        name='manage_awards'),
    url(r'^view_electee_surveys/(?P<term_id>\d+)/$',
        views.view_electee_surveys_for_term,
        name='view_electee_surveys_for_term'),
    url(r'^view_electee_surveys/$',
        views.view_electee_surveys,
        name='view_electee_surveys'),
    url(r'^manage_background_checks/$',
        views.add_background_checks,
        name='add_background_checks'),
    url(r'^manage_many_background_checks/$',
        views.mass_add_background_checks,
        name='mass_add_background_checks'),
    url(r'^download_member_data/$',
        views.download_member_data,
        name='download_member_data'),
    url(r'^download_member_data_email/$',
        views.download_member_data_email,
        name='download_member_data_email'),
    url(r'^download_active_status/$',
        views.download_active_status,
        name='download_active_status'),
    url(r'^download_elections_voters/$',
        views.download_elections_voters,
        name='download_elections_voters'),
    url(r'^view_electee_survey/(?P<uniqname>[a-z]{3,8})/$',
        views.view_electee_survey,
        name='view_electee_survey'),
    url(r'^manage_committee_members/(?P<term_id>\d+)/$',
        views.manage_committee_members,
        name='manage_committee_members'),
    url(r'^edit_project_reports/(?P<term_id>\d+)/$',
        views.edit_project_reports,
        name='edit_project_reports'),
    url(r'^manage_committees/$',
        views.manage_committees,
        name='manage_committees'),
    url(r'^view_photos/$',
        views.view_photos,
        name='view_photos'),
    url(r'^manage_alumni_status/$',
        views.manage_alumni_status,
        name='manage_alumni_status'),
]

migweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from migweb import views
from event_cal import views as ev_views
admin.autodiscover()

urlpatterns = [
    url(r'^$',
        views.home, name='home'),
    url(r'^career_fair/companies/$',
        views.cf_companies, name='cf_companies'),
    url(r'^about/',
        include('about.urls', namespace='about')),
    url(r'^outreach/',
        include('outreach.urls', namespace='outreach')),
    url(r'^publications/',
        include('history.urls', namespace='history')),
    url(r'^corporate/',
        include('corporate.urls', namespace='corporate')),
    url(r'^calendar/',
        include('event_cal.urls', namespace='event_cal')),
    url(r'^members/elections/',
        include('elections.urls', namespace='elections')),
    url(r'^members/electees/',
        include('electees.urls', namespace='electees')),
    url(r'^members/playground/',
        include('fora.urls', namespace='fora')),
    # url(r'^bookswap/',
        # include('bookswap.urls', namespace='bookswap')),
    url(r'^members/',
        include('member_resources.urls', namespace='member_resources')),
    #url(r'^admin/plate/', include('django_spaghetti.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', views.login_view, name='login_view'),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'mig_main/login.html'}),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),
    url(r'^oauth2callback/$', ev_views.oauth, name='oauth'),
    url(r'^townhalls/$', RedirectView.as_view(url='/outreach/townhalls/')),
    url(r'^pi_day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^pi-day/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^piday/$', RedirectView.as_view(url='/outreach/pi_day/')),
    url(r'^twitter_oauth/$',
        views.twitter_oauth,
        name='twitter_oauth'),
    url(r'^init_twitter/$',
        views.initialize_twitter,
        name='initialize_twitter'),
    url(r'^slide_ajax/(?P<slide_id>\d+)/$',
        views.get_slide_ajax,
        name='get_slide_ajax'),
    url(r'^photo_ajax/(?P<photo_id>\d+)/$',
        views.get_eventphoto_ajax,
        name='get_eventphoto_ajax'),
    url(r'^article_photo_ajax/(?P<photo_id>\d+)/$',
        views.get_article_photo_ajax,
        name='get_article_photo_ajax'),
    url(r'^select2/', include('django_select2.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event_cal/templates/event_cal/detail.html
{% extends "event_cal/base_event_cal.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/datepicker.css' %}" />
{% if formset %}
{{form.media.css}}
{% endif %}
{% endblock css %}
{% block js %}
<script>
    function addtext(img_url,img_title,text_id) {
        var newtext="!["+img_title+"]("+img_url+" \""+img_title+"\")\n";
        var caretPos = document.getElementById(text_id).selectionStart;
        var textAreaTxt = jQuery("#"+text_id).val();
        jQuery("#"+text_id).val(textAreaTxt.substring(0,caretPos)+newtext+textAreaTxt.substring(caretPos));
    }
</script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
{% include 'datepicker.html' %}
{% if formset %}
{{form.media.js}}
{% endif %}
{% endblock js %}
{% block cal_content %}
{% if not edit %}
    {% with full_view=True %}
        {% include 'event_cal/event.html' %}
    {% endwith %}
    {% if can_add_sign_in %}
        <a class="btn btn-primary btn-lg" href="{% url 'event_cal:create_meeting_signin' event.id %}">Add meeting sign-in</a>
    {% endif %}
    {% if can_complete %}
        <a class="btn btn-success btn-lg" href="{% url 'event_cal:complete_event' event.id %}">Complete Event and Assign Hours</a>
    {% endif %}
    {% if can_edit_event or can_edit_reports %}
    {% if event.completed %}
    <a class="btn btn-info btn-lg" href="{% url 'event_cal:event_project_report' event.id %}">Add/Update Project Report</a>
    <a class="btn btn-warning btn-lg" href="{% url 'event_cal:update_completed_event' event.id %}">Update Event Progress</a>
    <a class="btn btn-info btn-lg" href="{% url 'event_cal:add_project_report_to_event' event.id %}">Add/Swap Existing Project Report</a>
    {% endif %}
    <a class="btn btn-primary btn-lg" href = "{% url 'event_cal:email_participants' event.id %}">Email Event Participants</a>
    {% if can_edit_signin %}
    <a class="btn btn-primary btn-lg" href = "{% url 'event_cal:create_meeting_signin' event.id %}">Edit Sign-In Code/Question</a>
    {% endif %}
    {% endif %}
{% else %}
<h3>{{event.name}}</h3>
<div class="dropdown">
    <a class="btn btn-default" id="photoSelect" role="button" data-toggle="dropdown" href="#">Add Photo <span class="caret"></span></a>
    <ul id="menu1" class="dropdown-menu scrollable-menu" role="menu" aria-labelledby="photoSelect">
    {% for photo in event_photos %}
        <li role="presentation"><img style="max-width:200px;" role="menuitem" tabindex="-1" src="{{photo.photo.thumbnail.url}}"></img>
        <div class="btn-group">
            <button type="button" class="btn-default" onClick="addtext('{{photo.photo.thumbnail.url}}','{{photo.caption|escapejs}}','id_event-description')">Add to Description</button>
            <button type="button" class="btn-default" onClick="addtext('{{photo.photo.thumbnail.url}}','{{photo.caption|escapejs}}','id_event-announce_text')">Add to Announcement</button>
        </div>
        <hr/></li>
    {% endfor %}
     </ul>
</div>
<form action="{% url 'event_cal:edit_event' event.id %}" method="post" id="dynForm">{% csrf_token %}
    {% include 'event_cal/event_form.html' %}
</form>
{% endif %}

{% endblock cal_content %}

event_cal/templates/event_cal/interview_sign_in.html
<ul>
{% for interviewee in actual_shift.attendees.all %}
    {% url 'member_resources:profile' interviewee.uniqname as profile_url %}
    <li id="shift-{{actual_shift.id}}-attendee-{{interviewee.uniqname}}">
    {% if interviewee.is_member %}
        <p><a href="{{profile_url}}">{{interviewee}}</a>{% if interviewee in actual_shift.event.get_users_who_can_bring_items %} <span class="text-success">(can bring item)</span>{% elif interviewee in actual_shift.event.get_users_who_cannot_bring_items %} <span class="text-danger">(cannot bring item)</span>{%endif%} {% if can_edit_event %}<a id="shift-{{actual_shift.id}}-user-{{interviewee.uniqname}}-remove" class="btn btn-small btn-danger confirmation" onclick="$('#shift-{{actual_shift.id}}-user-{{interviewee.uniqname}}-remove').attr('disabled',true);ajaxGet('{% if is_shift_two_part %}{% url 'event_cal:manual_remove_user_from_paired_shift' shift.id interviewee.uniqname %}{%else%}{% url 'event_cal:manual_remove_user_from_shift' actual_shift.id interviewee.uniqname %}{%endif%}')">Remove interviewe{% if is_interviewer %}r{%else%}e{%endif%}</a>{% endif %}</p>
    {% else %}
        <p>{{interviewee}}{% if interviewee in actual_shift.event.get_users_who_can_bring_items %} <span class="text-success">(can bring item)</span>{% elif interviewee in actual_shift.event.get_users_who_cannot_bring_items %} <span class="text-danger">(cannot bring item)</span>{%endif%}  {% if can_edit_event %}<a id="shift-{{actual_shift.id}}-user-{{interviewee.uniqname}}-remove" class="btn btn-small btn-danger confirmation" onclick="$('#shift-{{actual_shift.id}}-user-{{interviewee.uniqname}}-remove').attr('disabled',true);ajaxGet('{% if is_shift_two_part %}{% url 'event_cal:manual_remove_user_from_paired_shift'  shift.id interviewee.uniqname %}{%else%}{% url 'event_cal:manual_remove_user_from_paired_shift'  actual_shift.id interviewee.uniqname %}{%endif%}')">Remove interviewe{% if is_interviewer %}r{%else%}e{%endif%}</a>{% endif %}</p>
    {% endif %}
    </li>
{% empty %}
    {% if is_interviewer %}
    <p>No Interviewers yet</p>
    {% else %}
    <p>Interview Slot Open</p>
    {% endif %}
{% endfor %}
</ul>
{% if not actual_shift.is_full or user.userprofile in actual_shift.attendees.all %}
{% if user.is_authenticated and has_profile %}
    {% if user.userprofile.is_member and user.userprofile.memberprofile in event.get_attendees_with_progress %}
        {% if event.use_sign_in %}
            <p>You are already signed in to the event.</p>
        {% else %}
            <p>You have already received credit for this event.</p>
        {% endif %}
    {% elif user.userprofile in actual_shift.attendees.all %}
        {% if actual_shift.is_before_start %}
            {% if is_shift_two_part %}
                <p><a id="shift-signup{{actual_shift.id}}" class="btn btn-primary btn-sm" onclick="$('#shift-signup{{actual_shift.id}}').attr('disabled',true);ajaxGet('{% url 'event_cal:unsign_up_paired' shift.id %}',function(){$('#shift-signup{{actual_shift.id}}').attr('disabled',false);})"><i class="glyphicon glyphicon-remove"></i> Unsign-up</a></p>
            {% else %}
                <p><a id="shift-signup{{actual_shift.id}}" class="btn btn-primary btn-sm" onclick="$('#shift-signup{{actual_shift.id}}').attr('disabled',true);ajaxGet('{% url 'event_cal:unsign_up' actual_shift.id %}',function(){$('#shift-signup{{actual_shift.id}}').attr('disabled',false);})"><i class="glyphicon glyphicon-remove"></i> Unsign-up</a></p>
            {% endif %}
        {% else %}
            <p>You cannot unsign-up after the event has started</p>
        {% endif %}
        {% if show_manual_add_gcal_button %}
            {% if is_shift_two_part %}
            <p><a id="shift-gcal{{actual_shift.id}}" class="btn btn-primary btn-sm" onclick="$('#shift-gcal{{actual_shift.id}}').attr('disabled',true);ajaxGet('{% url 'event_cal:add_shift_to_gcal_paired'  shift.id %}',function(){$('#shift-gcal{{actual_shift.id}}').attr('disabled',false);})"><i class="glyphicon glyphicon-calendar"></i> Add to gcal</a></p>
            {% else %}
            <p><a id="shift-gcal{{actual_shift.id}}" class="btn btn-primary btn-sm" onclick="$('#shift-gcal{{actual_shift.id}}').attr('disabled',true);ajaxGet('{% url 'event_cal:add_shift_to_gcal'  actual_shift.id %}',function(){$('#shift-gcal{{actual_shift.id}}').attr('disabled',false);})"><i class="glyphicon glyphicon-calendar"></i> Add to gcal</a></p>
            {% endif %}
        {% endif %}
    {% elif actual_shift.ugrads_only and not user.userprofile.is_ugrad %}
        {% if user.userprofile.is_member %}
        <p>Shift is for {{actual_shift.get_restrictions}} only</p>
        {% else %}
        <p>Shift is members-only</p>
        {% endif %}
    {% elif actual_shift.grads_only and not user.userprofile.is_grad %}
        {% if user.userprofile.is_member %}
        <p>Shift is for {{actual_shift.get_restrictions}} only</p>
        {% else %}
        <p>Shift is members-only</p>
        {% endif %}
    {% elif actual_shift.electees_only and not user.userprofile.is_electee %}
        {% if user.userprofile.is_member %}
        <p>Shift is for {{actual_shift.get_restrictions}} only</p>
        {% else %}
        <p>Shift is members-only</p>
        {% endif %}
    {% elif actual_shift.actives_only and not user.userprofile.is_active %}
        {% if user.userprofile.is_member %}
        <p>Shift is for {{actual_shift.get_restrictions}} only</p>
        {% else %}
        <p>Shift is members-only</p>
        {% endif %}
    {% else %}
        {% if actual_shift.can_sign_up %}
            {% if is_shift_two_part %}
            <p><a id="shift-signup{{actual_shift.id}}" class="btn btn-primary btn-sm" onclick="$('#shift-signup{{actual_shift.id}}').attr('disabled',true);ajaxGet('{% url 'event_cal:sign_up_paired' shift.id %}',function(){$('#shift-signup{{actual_shift.id}}').attr('disabled',false);})"><i class="glyphicon glyphicon-ok"></i> Sign-up</a></p>
            {% else %}
            <p><a id="shift-signup{{actual_shift.id}}" class="btn btn-primary btn-sm" onclick="$('#shift-signup{{actual_shift.id}}').attr('disabled',true);ajaxGet('{% url 'event_cal:sign_up' actual_shift.id %}',function(){$('#shift-signup{{actual_shift.id}}').attr('disabled',false);})"><i class="glyphicon glyphicon-ok"></i> Sign-up</a></p>
            {% endif %}
            <p><a id="shift-gcal{{actual_shift.id}}" class="hidden"></a></p>
        {% else %}
            {% if not actual_shift.is_before_start %}
                <p>Sign up not allowed after the event starts.</p>
            {% elif actual_shift.is_full %}
                <p>Slot is full.</p>
            {% else %}
                <p>See, this is awkward. You can't sign in/up, but for the life of me I can't figure out why. You should tell the website chair...</p>
            {% endif %}
        {% endif %}
    {% endif %}
{% endif %}
{% endif %}